"""Shared fragments for Unreal Editor Python scripts.

The helpers use documented editor APIs: AssetTools, EditorAssetLibrary,
PCGGraph.add_node_of_type, and MaterialEditingLibrary. Node classes are
resolved with getattr so a missing class is reported instead of called.
"""

from __future__ import annotations

from nodebridge.common.random import unreal_random_library


def script_header(title: str, source: str) -> list[str]:
    return [
        f'"""{title}',
        "",
        source,
        "Target: Unreal Editor Python",
        "",
        "Run inside the Unreal Editor with the Python Editor Script plugin enabled.",
        "PCG graphs also need the PCG plugin. Materials use MaterialEditingLibrary.",
        "This builds a native asset. It does not import baked geometry.",
        "Equivalent results are procedurally related, not numerically identical.",
        '"""',
        "",
        "import unreal",
        "",
        unreal_random_library(),
        "",
        "def _try_set(settings, name, value):",
        "    if settings is None:",
        "        return False",
        "    try:",
        "        settings.set_editor_property(name, value)",
        "        return True",
        "    except Exception as exc:",
        "        unreal.log_warning(f'NodeBridge: could not set {name} on {settings.get_class().get_name()}: {exc}')",
        "        return False",
        "",
        "def _pin_labels(node, which):",
        "    labels = []",
        "    try:",
        "        pins = node.get_editor_property(which)",
        "    except Exception:",
        "        return labels",
        "    for pin in pins:",
        "        try:",
        "            props = pin.get_editor_property('properties')",
        "            labels.append(str(props.get_editor_property('label')))",
        "        except Exception:",
        "            continue",
        "    return labels",
        "",
        "def _connect(graph, source, source_labels, target, target_labels):",
        "    if source is None or target is None:",
        "        unreal.log_warning('NodeBridge: skipped a connection because a node was missing.')",
        "        return False",
        "    outputs = _pin_labels(source, 'output_pins')",
        "    inputs = _pin_labels(target, 'input_pins')",
        "    source_label = next((label for label in source_labels if label in outputs), outputs[0] if outputs else None)",
        "    target_label = next((label for label in target_labels if label in inputs), inputs[0] if inputs else None)",
        "    if source_label is None or target_label is None:",
        "        unreal.log_warning(",
        "            f'NodeBridge: could not connect {source_labels} -> {target_labels}. '",
        "            f'outputs={outputs} inputs={inputs}'",
        "        )",
        "        return False",
        "    graph.add_edge(source, source_label, target, target_label)",
        "    return True",
        "",
        "def _add(graph, class_name, x, y):",
        "    settings_cls = getattr(unreal, class_name, None)",
        "    if settings_cls is None:",
        "        unreal.log_error(f'NodeBridge: {class_name} is not available in this Unreal Python build.')",
        "        return None, None",
        "    node, settings = graph.add_node_of_type(settings_cls)",
        "    node.set_node_position(x, y)",
        "    return node, settings",
        "",
    ]
