"""Seed catalog of canonical semantic operations.

Operations describe *intent*, not a node widget in any particular
application. The catalog is intentionally narrow: a coherent vocabulary
is more valuable than a huge collection of unreliable mappings.

Host-specific node types belong in host mappings, never here.
"""

from __future__ import annotations

from nodebridge.core.operations import OperationSpec, ParameterSpec, PortSpec

P = PortSpec
A = ParameterSpec

_GEO_IN = P("geometry", "geometry", description="Incoming geometry.")
_GEO_OUT = P("geometry", "geometry", description="Resulting geometry.")
_VEC_IN = P("vector", "vector3")
_FLOAT_A = P("a", "float")
_FLOAT_B = P("b", "float", optional=True)
_FLOAT_OUT = P("value", "float")
_VEC_A = P("a", "vector3")
_VEC_B = P("b", "vector3", optional=True)
_VEC_OUT = P("vector", "vector3")

SEED_OPERATIONS: tuple[OperationSpec, ...] = (
    OperationSpec(
        "math.add",
        "math",
        "Component-wise or scalar addition.",
        inputs=(_FLOAT_A, _FLOAT_B),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "math.subtract",
        "math",
        "Component-wise or scalar subtraction.",
        inputs=(_FLOAT_A, _FLOAT_B),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "math.multiply",
        "math",
        "Component-wise or scalar multiplication.",
        inputs=(_FLOAT_A, _FLOAT_B),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "math.divide",
        "math",
        "Component-wise or scalar division.",
        inputs=(_FLOAT_A, _FLOAT_B),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "math.power",
        "math",
        "Raise a value to a power.",
        inputs=(_FLOAT_A, P("exponent", "float", optional=True)),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "math.min",
        "math",
        "Minimum of two values.",
        inputs=(_FLOAT_A, _FLOAT_B),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "math.max",
        "math",
        "Maximum of two values.",
        inputs=(_FLOAT_A, _FLOAT_B),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "math.clamp",
        "math",
        "Clamp a value between minimum and maximum bounds.",
        inputs=(
            P("value", "float"),
            P("min", "float", optional=True),
            P("max", "float", optional=True),
        ),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "math.map_range",
        "math",
        "Linearly remap a value from one range to another.",
        inputs=(
            P("value", "float"),
            P("from_min", "float", optional=True),
            P("from_max", "float", optional=True),
            P("to_min", "float", optional=True),
            P("to_max", "float", optional=True),
        ),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "vector.add",
        "vector",
        "Vector addition.",
        inputs=(_VEC_A, _VEC_B),
        outputs=(_VEC_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "vector.subtract",
        "vector",
        "Vector subtraction.",
        inputs=(_VEC_A, _VEC_B),
        outputs=(_VEC_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "vector.scale",
        "vector",
        "Scale a vector by a scalar.",
        inputs=(_VEC_IN, P("scale", "float", optional=True)),
        outputs=(_VEC_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "vector.normalize",
        "vector",
        "Unit-length vector.",
        inputs=(_VEC_IN,),
        outputs=(_VEC_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "vector.cross",
        "vector",
        "3D cross product.",
        inputs=(_VEC_A, _VEC_B),
        outputs=(_VEC_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "vector.dot",
        "vector",
        "Dot product.",
        inputs=(_VEC_A, _VEC_B),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "vector.distance",
        "vector",
        "Euclidean distance between two points.",
        inputs=(_VEC_A, _VEC_B),
        outputs=(_FLOAT_OUT,),
        field_behavior="broadcasts over fields",
        required_capabilities=("attributes",),
    ),
    OperationSpec(
        "geometry.transform",
        "geometry",
        "Apply a transform to geometry.",
        inputs=(
            _GEO_IN,
            P("translation", "vector3", optional=True),
            P("rotation", "vector3", optional=True),
            P("scale", "vector3", optional=True),
        ),
        outputs=(_GEO_OUT,),
        required_capabilities=("transforms", "mesh"),
        domain="geometry",
    ),
    OperationSpec(
        "geometry.join",
        "geometry",
        "Merge multiple geometries.",
        inputs=(_GEO_IN, P("geometry_001", "geometry", optional=True)),
        outputs=(_GEO_OUT,),
        required_capabilities=("mesh",),
        domain="geometry",
    ),
    OperationSpec(
        "geometry.separate",
        "geometry",
        "Split geometry by a selection or material.",
        inputs=(_GEO_IN, P("selection", "boolean", optional=True, field=True)),
        outputs=(
            P("true", "geometry"),
            P("false", "geometry", optional=True),
        ),
        required_capabilities=("mesh", "attributes"),
        domain="geometry",
    ),
    OperationSpec(
        "geometry.instance",
        "geometry",
        "Instance geometry on points.",
        aliases=("instance",),
        inputs=(
            P("points", "geometry"),
            P("instance", "geometry", optional=True),
            P("scale", "vector3", optional=True, field=True),
            P("rotation", "vector3", optional=True, field=True),
        ),
        outputs=(P("instances", "instances"),),
        required_capabilities=("instances",),
        instance_behavior="produces instances; does not realize them",
        domain="point",
    ),
    OperationSpec(
        "geometry.realize_instances",
        "geometry",
        "Convert instances into real geometry.",
        aliases=("realize_instances",),
        inputs=(P("geometry", "geometry"),),
        outputs=(_GEO_OUT,),
        required_capabilities=("instances", "mesh"),
        instance_behavior="consumes instances and emits realized geometry",
        domain="instance",
    ),
    OperationSpec(
        "geometry.modify_position",
        "geometry",
        "Write a new position field onto geometry.",
        inputs=(
            _GEO_IN,
            P("position", "vector3", optional=True, field=True),
            P("offset", "vector3", optional=True, field=True),
            P("selection", "boolean", optional=True, field=True),
        ),
        outputs=(_GEO_OUT,),
        required_capabilities=("attributes", "mesh"),
        field_behavior="evaluates position/offset as fields on the point domain",
        domain="point",
    ),
    OperationSpec(
        "geometry.primitive",
        "geometry",
        "Create a primitive mesh (cube, grid, sphere, …).",
        inputs=(),
        outputs=(_GEO_OUT,),
        parameters=(
            A("primitive", "string", "cube", "Kind of primitive."),
            A("size", "float", 1.0),
        ),
        required_capabilities=("mesh",),
        domain="geometry",
    ),
    OperationSpec(
        "geometry.delete",
        "geometry",
        "Delete or filter elements by a selection.",
        aliases=("geometry.filter",),
        inputs=(_GEO_IN, P("selection", "boolean", optional=True, field=True)),
        outputs=(_GEO_OUT,),
        parameters=(A("domain", "string", "point"), A("mode", "string", "all")),
        required_capabilities=("mesh", "attributes"),
        domain="point",
    ),
    OperationSpec(
        "points.distribute",
        "points",
        "Distribute or sample points on a surface.",
        aliases=("surface_sample", "geometry.distribute_points"),
        inputs=(
            P("geometry", "geometry"),
            P("density", "float", optional=True, field=True),
            P("seed", "integer", optional=True),
        ),
        outputs=(P("points", "points"),),
        parameters=(
            A("density", "float", 10.0),
            A("seed", "integer", 0),
            A("method", "string", "random"),
        ),
        deterministic=True,
        required_capabilities=("point_data", "mesh"),
        domain="face",
    ),
    OperationSpec(
        "random.float",
        "random",
        "Generate a random float, optionally as a field.",
        inputs=(
            P("min", "float", optional=True),
            P("max", "float", optional=True),
            P("id", "integer", optional=True, field=True),
            P("seed", "integer", optional=True),
        ),
        outputs=(_FLOAT_OUT,),
        parameters=(A("min", "float", 0.0), A("max", "float", 1.0), A("seed", "integer", 0)),
        deterministic=True,
        required_capabilities=("randomness",),
        field_behavior="id-driven field when an id input is present",
    ),
    OperationSpec(
        "random.integer",
        "random",
        "Generate a random integer, optionally as a field.",
        inputs=(
            P("min", "integer", optional=True),
            P("max", "integer", optional=True),
            P("id", "integer", optional=True, field=True),
            P("seed", "integer", optional=True),
        ),
        outputs=(P("value", "integer"),),
        parameters=(A("min", "integer", 0), A("max", "integer", 1), A("seed", "integer", 0)),
        deterministic=True,
        required_capabilities=("randomness",),
    ),
    OperationSpec(
        "random.vector",
        "random",
        "Generate a random vector, optionally as a field.",
        aliases=("random",),
        inputs=(
            P("min", "vector3", optional=True),
            P("max", "vector3", optional=True),
            P("id", "integer", optional=True, field=True),
            P("seed", "integer", optional=True),
        ),
        outputs=(_VEC_OUT,),
        parameters=(
            A("min", "vector3", [0.0, 0.0, 0.0]),
            A("max", "vector3", [1.0, 1.0, 1.0]),
            A("seed", "integer", 0),
        ),
        deterministic=True,
        required_capabilities=("randomness",),
        field_behavior="id-driven field when an id input is present",
    ),
    OperationSpec(
        "attribute.read",
        "attribute",
        "Read a named attribute as a field.",
        inputs=(_GEO_IN,),
        outputs=(P("value", "field"), P("geometry", "geometry", optional=True)),
        parameters=(A("name", "string", ""), A("domain", "string", "point")),
        required_capabilities=("attributes",),
        field_behavior="produces a field on the requested domain",
        domain="point",
    ),
    OperationSpec(
        "attribute.write",
        "attribute",
        "Write a field onto a named attribute.",
        inputs=(
            _GEO_IN,
            P("value", "field", optional=True, field=True),
            P("selection", "boolean", optional=True, field=True),
        ),
        outputs=(_GEO_OUT,),
        parameters=(A("name", "string", ""), A("domain", "string", "point")),
        required_capabilities=("attributes",),
        field_behavior="consumes a field and stores it as an attribute",
        domain="point",
    ),
    OperationSpec(
        "attribute.evaluate",
        "attribute",
        "Evaluate a field onto a domain.",
        aliases=("evaluate_field",),
        inputs=(_GEO_IN, P("value", "field", field=True)),
        outputs=(P("value", "field"),),
        required_capabilities=("attributes", "fields"),
        field_behavior="forces field evaluation onto geometry",
    ),
    OperationSpec(
        "attribute.transfer",
        "attribute",
        "Transfer an attribute from one geometry to another.",
        inputs=(
            P("source", "geometry"),
            P("destination", "geometry", optional=True),
            P("source_value", "field", optional=True, field=True),
        ),
        outputs=(P("value", "field"), P("geometry", "geometry", optional=True)),
        parameters=(A("name", "string", ""), A("mapping", "string", "nearest")),
        required_capabilities=("attributes",),
        domain="point",
    ),
    OperationSpec(
        "selection.compare",
        "selection",
        "Build a boolean selection.",
        inputs=(P("a", "float"), P("b", "float", optional=True)),
        outputs=(P("result", "boolean"),),
        parameters=(A("operation", "string", "greater_than"),),
        required_capabilities=("attributes",),
        field_behavior="broadcasts over fields",
    ),
    OperationSpec(
        "procedural.noise",
        "procedural",
        "Procedural noise field.",
        inputs=(P("vector", "vector3", optional=True),),
        outputs=(_FLOAT_OUT,),
        required_capabilities=("attributes",),
        field_behavior="evaluates as a field",
    ),
    OperationSpec(
        "procedural.voronoi",
        "procedural",
        "Voronoi / Worley field.",
        inputs=(P("vector", "vector3", optional=True),),
        outputs=(_FLOAT_OUT,),
        required_capabilities=("attributes",),
        field_behavior="evaluates as a field",
    ),
    OperationSpec(
        "texture.sample",
        "texture",
        "Sample a texture at a coordinate.",
        inputs=(P("vector", "vector3", optional=True),),
        outputs=(P("color", "color"),),
        required_capabilities=("material",),
    ),
    OperationSpec(
        "shader.principled_surface",
        "shader",
        "Physically based surface shading model.",
        inputs=(
            P("base_color", "color", optional=True),
            P("roughness", "float", optional=True),
            P("metallic", "float", optional=True),
        ),
        outputs=(P("shader", "shader"),),
        required_capabilities=("material",),
    ),
    OperationSpec(
        "color.mix",
        "color",
        "Mix two colors.",
        inputs=(
            P("a", "color"),
            P("b", "color"),
            P("factor", "float", optional=True),
        ),
        outputs=(P("color", "color"),),
        required_capabilities=("material",),
    ),
    OperationSpec(
        "color.ramp",
        "color",
        "Map a scalar through a color ramp.",
        inputs=(P("factor", "float"),),
        outputs=(P("color", "color"),),
        required_capabilities=("material",),
    ),
    OperationSpec(
        "graph.input",
        "graph",
        "Exposed graph input.",
        outputs=(_GEO_OUT,),
        side_effects=False,
        deterministic=True,
    ),
    OperationSpec(
        "graph.output",
        "graph",
        "Exposed graph output.",
        inputs=(_GEO_IN,),
        side_effects=False,
        deterministic=True,
    ),
    OperationSpec(
        "graph.group",
        "graph",
        "Call a nested / reusable group.",
        side_effects=False,
    ),
    OperationSpec(
        "unknown",
        "unknown",
        "Unrecognized source operation.",
        deterministic=False,
    ),
)
