"""Host frontend/backend fixture tests."""

from __future__ import annotations

from nodebridge.hosts.blender import BlenderBackend, BlenderFrontend
from nodebridge.hosts.houdini import HoudiniBackend, HoudiniFrontend
from nodebridge.hosts.unreal import UnrealBackend, UnrealFrontend
from tests.helpers import make_blender_scatter_native, make_houdini_scatter_native, make_scatter_ir_graph


def _ops(document) -> set[str]:
    return {node.operation for node in document.graph.nodes.values()}


def test_blender_frontend_normalizes_scatter_semantics() -> None:
    document = BlenderFrontend().extract(make_blender_scatter_native())
    ops = _ops(document)
    assert "points.distribute" in ops
    assert "random.vector" in ops
    assert "geometry.instance" in ops
    assert "geometry.realize_instances" in ops
    assert "geometry.primitive" in ops
    dist = next(node for node in document.graph.nodes.values() if node.operation == "points.distribute")
    assert dist.metadata.provenance.original_type == "GeometryNodeDistributePointsOnFaces"


def test_houdini_frontend_normalizes_scatter_semantics() -> None:
    document = HoudiniFrontend().extract(make_houdini_scatter_native())
    ops = _ops(document)
    assert "points.distribute" in ops
    assert "geometry.instance" in ops
    assert "geometry.realize_instances" in ops
    assert "graph.input" in ops
    assert "graph.output" in ops


def test_blender_backend_emits_geometry_nodes() -> None:
    native = BlenderBackend().build(make_scatter_ir_graph().graph)
    types = {node.type for node in native.nodes}
    assert "GeometryNodeDistributePointsOnFaces" in types
    assert "GeometryNodeInstanceOnPoints" in types
    assert "GeometryNodeRealizeInstances" in types
    assert "FunctionNodeRandomValue" in types
    script = BlenderBackend().generate(make_scatter_ir_graph().graph)
    assert "import bpy" in script
    assert "Generated by NodeBridge" in script


def test_houdini_backend_emits_sops() -> None:
    native = HoudiniBackend().build(make_scatter_ir_graph().graph)
    types = {node.type for node in native.nodes}
    assert "scatter" in types
    assert "copytopoints" in types
    assert "unpack" in types
    script = HoudiniBackend().generate(make_scatter_ir_graph().graph)
    assert "import hou" in script
    assert "createNode" in script


def test_unreal_backend_emits_pcg_plan_without_unreal() -> None:
    native = UnrealBackend().build(make_scatter_ir_graph().graph)
    types = {node.type for node in native.nodes}
    assert "PCGSurfaceSamplerSettings" in types
    assert "PCGStaticMeshSpawnerSettings" in types
    assert native.metadata.get("runtime") == "editor-only"
    script = UnrealBackend().generate(make_scatter_ir_graph().graph)
    assert "add_node_of_type" in script
    assert "unreal.PCGSurfaceSamplerSettings" in script
    document = UnrealFrontend().extract(native)
    assert "points.distribute" in _ops(document)
