"""NodeBridge: generated Unreal Editor Python.

Source:  Shader / ProceduralRock (Blender 4.2.23 LTS)
Target:  Unreal Engine 5 (Material asset)
Translation: 4 exact, 2 equivalent, 2 approximate, 0 unsupported
Generated by NodeBridge 0.3.0.

Run inside the Unreal Editor with the Python Editor Script Plugin enabled:
Window > Output Log > Python command line, or Tools > Execute Python Script.
New assets are created under ASSET_PATH; existing assets are never overwritten.
"""
import unreal

ASSET_PATH = "/Game/NodeBridge"
NB_WARNINGS = []


def nb_unique_asset_name(path, name):
    candidate, index = name, 1
    while unreal.EditorAssetLibrary.does_asset_exist("%s/%s" % (path, candidate)):
        index += 1
        candidate = "%s_%d" % (name, index)
    return candidate


def nb_create_asset(name, path, asset_class, factory):
    """Create a new asset; never overwrites an existing one."""
    unreal.EditorAssetLibrary.make_directory(path)
    name = nb_unique_asset_name(path, name)
    asset = unreal.AssetToolsHelpers.get_asset_tools().create_asset(name, path, asset_class, factory)
    if asset is None:
        raise RuntimeError("NodeBridge could not create %s/%s" % (path, name))
    return asset


def nb_class(name):
    cls = getattr(unreal, name, None)
    if cls is None:
        NB_WARNINGS.append("unreal.%s is not available in this Unreal version" % name)
    return cls


def nb_enum(enum_name, *candidates):
    enum = getattr(unreal, enum_name, None)
    for candidate in candidates:
        if enum is not None and hasattr(enum, candidate):
            return getattr(enum, candidate)
    NB_WARNINGS.append("unreal.%s has none of %s" % (enum_name, ", ".join(candidates)))
    return None


def nb_prop(obj, name, value):
    """set_editor_property with a warning instead of an exception."""
    if obj is None or value is None:
        return False
    try:
        obj.set_editor_property(name, value)
        return True
    except Exception as exc:
        NB_WARNINGS.append("%s.%s: %s" % (type(obj).__name__, name, exc))
        return False

MEL = unreal.MaterialEditingLibrary


def nb_expression(material, class_name, x, y):
    cls = nb_class(class_name)
    if cls is None:
        return None
    return MEL.create_material_expression(material, cls, x, y)


def nb_link(source, source_output, target, target_input):
    if source is None or target is None:
        return False
    if not MEL.connect_material_expressions(source, source_output, target, target_input):
        NB_WARNINGS.append("could not connect %s.%s -> %s.%s" % (type(source).__name__, source_output, type(target).__name__, target_input))
        return False
    return True


def nb_output(source, source_output, material_property):
    if source is None or material_property is None:
        return False
    if not MEL.connect_material_property(source, source_output, material_property):
        NB_WARNINGS.append("could not connect %s to %s" % (type(source).__name__, material_property))
        return False
    return True

def build_material_procedural_rock():
    """Material 'ProceduralRock' as an Unreal Material asset."""
    material = nb_create_asset("M_ProceduralRock", ASSET_PATH, unreal.Material, unreal.MaterialFactoryNew())
    # Principled BSDF: SHADER_BSDF -> material attributes
    # Rock Colors: COLOR_RAMP [EXACT]
    # Rock Noise: NOISE [APPROXIMATE]
    rock_noise = nb_expression(material, "MaterialExpressionNoise", -660, 140)
    # Mapping: MAPPING [EXACT]
    mapping_scale = nb_expression(material, "MaterialExpressionMultiply", -920, 280)
    # Texture Coordinate Object: FIELD_INPUT [EQUIVALENT]
    texture_coordinate_object = nb_expression(material, "MaterialExpressionLocalPosition", -1180, 420)
    texture_coordinate_object_to_blender_meters = nb_expression(material, "MaterialExpressionMultiply", -1440, 560)
    nb_link(texture_coordinate_object, '', texture_coordinate_object_to_blender_meters, 'A')
    constant3vector = nb_expression(material, "MaterialExpressionConstant3Vector", -1700, 700)
    nb_prop(constant3vector, "constant", unreal.LinearColor(0.01, -0.01, 0.01, 1.0))
    nb_link(constant3vector, '', texture_coordinate_object_to_blender_meters, 'B')
    nb_link(texture_coordinate_object_to_blender_meters, '', mapping_scale, 'A')
    constant3vector_2 = nb_expression(material, "MaterialExpressionConstant3Vector", -400, 840)
    nb_prop(constant3vector_2, "constant", unreal.LinearColor(2.0, 2.0, 2.0, 1.0))
    nb_link(constant3vector_2, '', mapping_scale, 'B')
    nb_link(mapping_scale, '', rock_noise, 'Position')
    nb_prop(rock_noise, "scale", 4.0)
    nb_prop(rock_noise, "levels", 9)
    nb_prop(rock_noise, "output_min", 0.0)
    nb_prop(rock_noise, "output_max", 1.0)
    nb_prop(rock_noise, "noise_function", nb_enum("NoiseFunction", "NOISEFUNCTION_GRADIENT_ALU", "GRADIENT_ALU"))
    constant3vector_3 = nb_expression(material, "MaterialExpressionConstant3Vector", -660, 980)
    nb_prop(constant3vector_3, "constant", unreal.LinearColor(0.08, 0.07, 0.06, 1.0))
    rock_colors_segment_1_shift = nb_expression(material, "MaterialExpressionSubtract", -920, 1120)
    nb_link(rock_noise, '', rock_colors_segment_1_shift, 'A')
    nb_prop(rock_colors_segment_1_shift, "const_b", 0.3)
    rock_colors_segment_1_scale = nb_expression(material, "MaterialExpressionMultiply", -1180, 1260)
    nb_link(rock_colors_segment_1_shift, '', rock_colors_segment_1_scale, 'A')
    nb_prop(rock_colors_segment_1_scale, "const_b", 5.0)
    rock_colors_segment_1_clamp = nb_expression(material, "MaterialExpressionSaturate", -1440, 1400)
    nb_link(rock_colors_segment_1_scale, '', rock_colors_segment_1_clamp, '')
    rock_colors_stop_1 = nb_expression(material, "MaterialExpressionLinearInterpolate", -1700, 1540)
    nb_link(constant3vector_3, '', rock_colors_stop_1, 'A')
    constant3vector_4 = nb_expression(material, "MaterialExpressionConstant3Vector", -400, 1680)
    nb_prop(constant3vector_4, "constant", unreal.LinearColor(0.25, 0.2, 0.15, 1.0))
    nb_link(constant3vector_4, '', rock_colors_stop_1, 'B')
    nb_link(rock_colors_segment_1_clamp, '', rock_colors_stop_1, 'Alpha')
    rock_colors_segment_2_shift = nb_expression(material, "MaterialExpressionSubtract", -660, 1820)
    nb_link(rock_noise, '', rock_colors_segment_2_shift, 'A')
    nb_prop(rock_colors_segment_2_shift, "const_b", 0.5)
    rock_colors_segment_2_scale = nb_expression(material, "MaterialExpressionMultiply", -920, 1960)
    nb_link(rock_colors_segment_2_shift, '', rock_colors_segment_2_scale, 'A')
    nb_prop(rock_colors_segment_2_scale, "const_b", 4.0)
    rock_colors_segment_2_clamp = nb_expression(material, "MaterialExpressionSaturate", -1180, 2100)
    nb_link(rock_colors_segment_2_scale, '', rock_colors_segment_2_clamp, '')
    rock_colors_stop_2 = nb_expression(material, "MaterialExpressionLinearInterpolate", -1440, 2240)
    nb_link(rock_colors_stop_1, '', rock_colors_stop_2, 'A')
    constant3vector_5 = nb_expression(material, "MaterialExpressionConstant3Vector", -1700, 2380)
    nb_prop(constant3vector_5, "constant", unreal.LinearColor(0.55, 0.5, 0.42, 1.0))
    nb_link(constant3vector_5, '', rock_colors_stop_2, 'B')
    nb_link(rock_colors_segment_2_clamp, '', rock_colors_stop_2, 'Alpha')
    nb_output(rock_colors_stop_2, '', unreal.MaterialProperty.MP_BASE_COLOR)
    constant = nb_expression(material, "MaterialExpressionConstant", -400, 2520)
    nb_prop(constant, "r", 0.0)
    nb_output(constant, '', unreal.MaterialProperty.MP_METALLIC)
    # Roughness Range: MAP_RANGE [EXACT]
    roughness_range_t_shift = nb_expression(material, "MaterialExpressionSubtract", -660, 2660)
    nb_link(rock_noise, '', roughness_range_t_shift, 'A')
    nb_prop(roughness_range_t_shift, "const_b", 0.0)
    roughness_range_t_scale = nb_expression(material, "MaterialExpressionMultiply", -920, 2800)
    nb_link(roughness_range_t_shift, '', roughness_range_t_scale, 'A')
    nb_prop(roughness_range_t_scale, "const_b", 1.0)
    roughness_range_t_clamp = nb_expression(material, "MaterialExpressionSaturate", -1180, 2940)
    nb_link(roughness_range_t_scale, '', roughness_range_t_clamp, '')
    roughness_range = nb_expression(material, "MaterialExpressionLinearInterpolate", -1440, 3080)
    nb_prop(roughness_range, "const_a", 0.45)
    param_roughness_scale = nb_expression(material, "MaterialExpressionScalarParameter", -1700, 3220)
    nb_prop(param_roughness_scale, "default_value", 0.9)
    nb_prop(param_roughness_scale, "parameter_name", 'Roughness Scale')
    nb_link(param_roughness_scale, '', roughness_range, 'B')
    nb_link(roughness_range_t_clamp, '', roughness_range, 'Alpha')
    nb_output(roughness_range, '', unreal.MaterialProperty.MP_ROUGHNESS)
    constant_2 = nb_expression(material, "MaterialExpressionConstant", -400, 3360)
    nb_prop(constant_2, "r", 0.5)
    nb_output(constant_2, '', unreal.MaterialProperty.MP_SPECULAR)
    # Rock Bump: BUMP [APPROXIMATE]
    rock_bump_ddx = nb_expression(material, "MaterialExpressionDDX", -660, 3500)
    nb_link(rock_noise, '', rock_bump_ddx, '')
    rock_bump_ddy = nb_expression(material, "MaterialExpressionDDY", -920, 3640)
    nb_link(rock_noise, '', rock_bump_ddy, '')
    rock_bump_gx = nb_expression(material, "MaterialExpressionMultiply", -1180, 3780)
    nb_link(rock_bump_ddx, '', rock_bump_gx, 'A')
    nb_prop(rock_bump_gx, "const_b", -35.0)
    rock_bump_gy = nb_expression(material, "MaterialExpressionMultiply", -1440, 3920)
    nb_link(rock_bump_ddy, '', rock_bump_gy, 'A')
    nb_prop(rock_bump_gy, "const_b", -35.0)
    rock_bump_xy = nb_expression(material, "MaterialExpressionAppendVector", -1700, 4060)
    nb_link(rock_bump_gx, '', rock_bump_xy, 'A')
    nb_link(rock_bump_gy, '', rock_bump_xy, 'B')
    rock_bump_xyz = nb_expression(material, "MaterialExpressionAppendVector", -400, 4200)
    nb_link(rock_bump_xy, '', rock_bump_xyz, 'A')
    constant_3 = nb_expression(material, "MaterialExpressionConstant", -660, 4340)
    nb_prop(constant_3, "r", 1.0)
    nb_link(constant_3, '', rock_bump_xyz, 'B')
    rock_bump_normal = nb_expression(material, "MaterialExpressionNormalize", -920, 4480)
    nb_link(rock_bump_xyz, '', rock_bump_normal, '')
    nb_output(rock_bump_normal, '', unreal.MaterialProperty.MP_NORMAL)
    MEL.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
    return material

def build():
    return build_material_procedural_rock()

material = build()
print("NodeBridge: created", material.get_path_name())
for nb_warning in NB_WARNINGS:
    unreal.log_warning("NodeBridge: " + nb_warning)
