"""NodeBridge: generated Houdini Python.

Source:  Shader / ProceduralRock (Blender 4.2.23 LTS)
Target:  Houdini (MaterialX material in /mat)
Translation: 4 exact, 3 equivalent, 1 approximate, 0 unsupported
Generated by NodeBridge 0.3.0.

Run inside Houdini: Windows > Python Source Editor, paste this script, click Apply.
The script only creates new nodes; existing scene content is not modified.
Equivalent / approximate operations are marked with sticky notes in the network.
"""
import hou

NB_WARNINGS = []
NB_NOTES = []


def nb_unique_name(parent, name):
    """Never overwrite existing nodes: append a number if the name is taken."""
    candidate, index = name, 1
    while parent.node(candidate) is not None:
        index += 1
        candidate = "%s%d" % (name, index)
    return candidate


def nb_create(parent, node_type, name, **kwargs):
    return parent.createNode(node_type, nb_unique_name(parent, name), **kwargs)


def nb_set(node, parm_name, value):
    """Set a parameter (or parameter tuple) if this Houdini version has it."""
    if isinstance(value, (tuple, list)):
        parm_tuple = node.parmTuple(parm_name)
        if parm_tuple is not None:
            parm_tuple.set(value)
            return True
    parm = node.parm(parm_name)
    if parm is not None:
        parm.set(value)
        return True
    NB_WARNINGS.append("%s: parameter '%s' not found" % (node.path(), parm_name))
    return False


def nb_set_menu(node, parm_name, token):
    """Set a menu parameter by token, whether the menu stores strings or indices."""
    parm = node.parm(parm_name)
    if parm is None:
        NB_WARNINGS.append("%s: parameter '%s' not found" % (node.path(), parm_name))
        return False
    tokens = parm.menuItems()
    if token not in tokens:
        NB_WARNINGS.append("%s: '%s' is not an option of '%s' (%s)" % (node.path(), token, parm_name, ", ".join(tokens)))
        return False
    if parm.parmTemplate().dataType() == hou.parmData.String:
        parm.set(token)
    else:
        parm.set(tokens.index(token))
    return True


def nb_expr(node, parm_name, expression, index=None):
    """Drive a parameter with an HScript expression (e.g. a channel reference)."""
    if index is None:
        parm = node.parm(parm_name)
    else:
        parm_tuple = node.parmTuple(parm_name)
        parm = parm_tuple[index] if parm_tuple is not None else None
    if parm is None:
        NB_WARNINGS.append("%s: parameter '%s' not found for expression" % (node.path(), parm_name))
        return False
    parm.setExpression(expression, hou.exprLanguage.Hscript)
    return True


def nb_add_parameters(node, folder_label, templates):
    """Expose controls as spare parameters on a container node."""
    if not templates:
        return
    group = node.parmTemplateGroup()
    folder = hou.FolderParmTemplate("nodebridge_controls", folder_label, folder_type=hou.folderType.Tabs)
    for template in templates:
        folder.addParmTemplate(template)
    group.append(folder)
    node.setParmTemplateGroup(group)


def nb_note(parent, text, near=None):
    note = parent.createStickyNote()
    note.setText(text)
    NB_NOTES.append((note, near))
    return note


def nb_place_notes():
    for note, near in NB_NOTES:
        if near is not None:
            note.setPosition(near.position() + hou.Vector2(2.0, -0.5))
        note.setSize(hou.Vector2(5.0, 1.6))


def nb_connect(node, input_name, source, output=0):
    """Connect by input name (VOP networks); report instead of failing."""
    try:
        node.setNamedInput(input_name, source, output)
        return True
    except hou.Error as exc:
        NB_WARNINGS.append("%s: could not connect '%s' (%s)" % (node.path(), input_name, exc))
        return False


def nb_meta(node, comment, data):
    node.setComment(comment)
    node.setGenericFlag(hou.nodeFlag.DisplayComment, True)
    node.setUserData("nodebridge", data)

def build_material_procedural_rock():
    """Material 'ProceduralRock' as a MaterialX network in /mat."""
    matnet = hou.node("/mat")
    # Principled BSDF: SHADER_BSDF [EQUIVALENT]
    procedural_rock = nb_create(matnet, "mtlxstandard_surface", "procedural_rock")
    # Rock Colors: COLOR_RAMP [EXACT]
    rock_colors_stop_0 = nb_create(matnet, "mtlxconstant", "rock_colors_stop_0")
    nb_set_menu(rock_colors_stop_0, "signature", "color3")
    nb_set(rock_colors_stop_0, "value", (0.08, 0.07, 0.06))
    rock_colors_segment_1 = nb_create(matnet, "mtlxremap", "rock_colors_segment_1")
    # Rock Noise: NOISE [APPROXIMATE]
    rock_noise_scale = nb_create(matnet, "mtlxmultiply", "rock_noise_scale")
    nb_set_menu(rock_noise_scale, "signature", "vector3")
    nb_set_menu(rock_noise_scale, "signature", "vector3FA")
    # Mapping: MAPPING [EXACT]
    mapping_scale = nb_create(matnet, "mtlxmultiply", "mapping_scale")
    nb_set_menu(mapping_scale, "signature", "vector3")
    # Texture Coordinate Object: FIELD_INPUT [EQUIVALENT]
    texture_coordinate_object = nb_create(matnet, "mtlxposition", "texture_coordinate_object")
    nb_set_menu(texture_coordinate_object, "signature", "vector3")
    nb_set_menu(texture_coordinate_object, "space", "object")
    nb_connect(mapping_scale, "in1", texture_coordinate_object, 0)
    nb_set(mapping_scale, "in2", (2.0, 2.0, 2.0))
    mapping_offset = nb_create(matnet, "mtlxadd", "mapping_offset")
    nb_set_menu(mapping_offset, "signature", "vector3")
    nb_connect(mapping_offset, "in1", mapping_scale, 0)
    nb_set(mapping_offset, "in2", (0.0, 0.0, 0.0))
    nb_connect(rock_noise_scale, "in1", mapping_offset, 0)
    nb_set(rock_noise_scale, "in2", 4.0)
    rock_noise = nb_create(matnet, "mtlxfractal3d", "rock_noise")
    nb_connect(rock_noise, "position", rock_noise_scale, 0)
    nb_set(rock_noise, "octaves", 9)
    nb_set(rock_noise, "diminish", 0.6)
    nb_set(rock_noise, "lacunarity", 2.0)
    rock_noise_to_unit = nb_create(matnet, "mtlxremap", "rock_noise_to_unit")
    nb_connect(rock_noise_to_unit, "in", rock_noise, 0)
    nb_set(rock_noise_to_unit, "inlow", -1.0)
    nb_set(rock_noise_to_unit, "inhigh", 1.0)
    nb_connect(rock_colors_segment_1, "in", rock_noise_to_unit, 0)
    nb_set(rock_colors_segment_1, "inlow", 0.3)
    nb_set(rock_colors_segment_1, "inhigh", 0.5)
    rock_colors_segment_1_clamp = nb_create(matnet, "mtlxclamp", "rock_colors_segment_1_clamp")
    nb_connect(rock_colors_segment_1_clamp, "in", rock_colors_segment_1, 0)
    rock_colors_stop_1 = nb_create(matnet, "mtlxmix", "rock_colors_stop_1")
    nb_set_menu(rock_colors_stop_1, "signature", "color3")
    nb_connect(rock_colors_stop_1, "bg", rock_colors_stop_0, 0)
    nb_set(rock_colors_stop_1, "fg", (0.25, 0.2, 0.15))
    nb_connect(rock_colors_stop_1, "mix", rock_colors_segment_1_clamp, 0)
    rock_colors_segment_2 = nb_create(matnet, "mtlxremap", "rock_colors_segment_2")
    nb_connect(rock_colors_segment_2, "in", rock_noise_to_unit, 0)
    nb_set(rock_colors_segment_2, "inlow", 0.5)
    nb_set(rock_colors_segment_2, "inhigh", 0.75)
    rock_colors_segment_2_clamp = nb_create(matnet, "mtlxclamp", "rock_colors_segment_2_clamp")
    nb_connect(rock_colors_segment_2_clamp, "in", rock_colors_segment_2, 0)
    rock_colors_stop_2 = nb_create(matnet, "mtlxmix", "rock_colors_stop_2")
    nb_set_menu(rock_colors_stop_2, "signature", "color3")
    nb_connect(rock_colors_stop_2, "bg", rock_colors_stop_1, 0)
    nb_set(rock_colors_stop_2, "fg", (0.55, 0.5, 0.42))
    nb_connect(rock_colors_stop_2, "mix", rock_colors_segment_2_clamp, 0)
    nb_connect(procedural_rock, "base_color", rock_colors_stop_2, 0)
    nb_set(procedural_rock, "metalness", 0.0)
    # Roughness Range: MAP_RANGE [EXACT]
    roughness_range = nb_create(matnet, "mtlxremap", "roughness_range")
    nb_connect(roughness_range, "in", rock_noise_to_unit, 0)
    nb_set(roughness_range, "inlow", 0.0)
    nb_set(roughness_range, "inhigh", 1.0)
    nb_set(roughness_range, "outlow", 0.45)
    roughness_scale = nb_create(matnet, "mtlxconstant", "roughness_scale")
    nb_set(roughness_scale, "value", 0.9)
    nb_connect(roughness_range, "outhigh", roughness_scale, 0)
    roughness_range_clamp = nb_create(matnet, "mtlxclamp", "roughness_range_clamp")
    nb_connect(roughness_range_clamp, "in", roughness_range, 0)
    nb_set(roughness_range_clamp, "low", 0.45)
    nb_connect(roughness_range_clamp, "high", roughness_scale, 0)
    nb_connect(procedural_rock, "specular_roughness", roughness_range_clamp, 0)
    nb_set(procedural_rock, "specular_IOR", 1.5)
    # Rock Bump: BUMP [EQUIVALENT]
    rock_bump = nb_create(matnet, "mtlxheighttonormal", "rock_bump")
    nb_connect(rock_bump, "in", rock_noise_to_unit, 0)
    nb_set(rock_bump, "scale", 0.35)
    nb_connect(procedural_rock, "normal", rock_bump, 0)
    nb_set(procedural_rock, "emission_color", (1.0, 1.0, 1.0))
    nb_set(procedural_rock, "emission", 0.0)
    nb_set(procedural_rock, "transmission", 0.0)
    nb_set(procedural_rock, "coat", 0.0)
    nb_set(procedural_rock, "coat_roughness", 0.03)
    nb_set(procedural_rock, "sheen", 0.0)
    nb_set(procedural_rock, "subsurface", 0.0)
    nb_set(procedural_rock, "specular", 1.0)
    nb_set(procedural_rock, "opacity", (1.0, 1.0, 1.0))
    material_nodes = (
        procedural_rock,
        rock_colors_stop_0,
        rock_colors_segment_1,
        rock_noise_scale,
        mapping_scale,
        texture_coordinate_object,
        mapping_offset,
        rock_noise,
        rock_noise_to_unit,
        rock_colors_segment_1_clamp,
        rock_colors_stop_1,
        rock_colors_segment_2,
        rock_colors_segment_2_clamp,
        rock_colors_stop_2,
        roughness_range,
        roughness_scale,
        roughness_range_clamp,
        rock_bump,
    )
    matnet.layoutChildren(items=material_nodes)
    nb_box = matnet.createNetworkBox()
    for nb_item in material_nodes:
        nb_box.addItem(nb_item)
    nb_box.setComment('ProceduralRock')
    nb_box.fitAroundContents()
    return procedural_rock

def build():
    return build_material_procedural_rock()

material = build()
print("NodeBridge: created material", material.path())
for nb_warning in NB_WARNINGS:
    print("NodeBridge warning:", nb_warning)
