"""NodeBridge: generated Houdini Python.

Source:  Compositor / Scene Compositor (Blender 4.2.23 LTS)
Target:  Houdini (COP2 network in /img)
Translation: 0 exact, 1 equivalent, 2 approximate, 2 unsupported
Generated by NodeBridge 0.3.0.

Run inside Houdini: Windows > Python Source Editor, paste this script, click Apply.
The script only creates new nodes; existing scene content is not modified.
Equivalent / approximate operations are marked with sticky notes in the network.
"""
import hou

NB_WARNINGS = []
NB_NOTES = []


def nb_unique_name(parent, name):
    """Never overwrite existing nodes: append a number if the name is taken."""
    candidate, index = name, 1
    while parent.node(candidate) is not None:
        index += 1
        candidate = "%s%d" % (name, index)
    return candidate


def nb_create(parent, node_type, name, **kwargs):
    return parent.createNode(node_type, nb_unique_name(parent, name), **kwargs)


def nb_set(node, parm_name, value):
    """Set a parameter (or parameter tuple) if this Houdini version has it."""
    if isinstance(value, (tuple, list)):
        parm_tuple = node.parmTuple(parm_name)
        if parm_tuple is not None:
            parm_tuple.set(value)
            return True
    parm = node.parm(parm_name)
    if parm is not None:
        parm.set(value)
        return True
    NB_WARNINGS.append("%s: parameter '%s' not found" % (node.path(), parm_name))
    return False


def nb_set_menu(node, parm_name, token):
    """Set a menu parameter by token, whether the menu stores strings or indices."""
    parm = node.parm(parm_name)
    if parm is None:
        NB_WARNINGS.append("%s: parameter '%s' not found" % (node.path(), parm_name))
        return False
    tokens = parm.menuItems()
    if token not in tokens:
        NB_WARNINGS.append("%s: '%s' is not an option of '%s' (%s)" % (node.path(), token, parm_name, ", ".join(tokens)))
        return False
    if parm.parmTemplate().dataType() == hou.parmData.String:
        parm.set(token)
    else:
        parm.set(tokens.index(token))
    return True


def nb_expr(node, parm_name, expression, index=None):
    """Drive a parameter with an HScript expression (e.g. a channel reference)."""
    if index is None:
        parm = node.parm(parm_name)
    else:
        parm_tuple = node.parmTuple(parm_name)
        parm = parm_tuple[index] if parm_tuple is not None else None
    if parm is None:
        NB_WARNINGS.append("%s: parameter '%s' not found for expression" % (node.path(), parm_name))
        return False
    parm.setExpression(expression, hou.exprLanguage.Hscript)
    return True


def nb_add_parameters(node, folder_label, templates):
    """Expose controls as spare parameters on a container node."""
    if not templates:
        return
    group = node.parmTemplateGroup()
    folder = hou.FolderParmTemplate("nodebridge_controls", folder_label, folder_type=hou.folderType.Tabs)
    for template in templates:
        folder.addParmTemplate(template)
    group.append(folder)
    node.setParmTemplateGroup(group)


def nb_note(parent, text, near=None):
    note = parent.createStickyNote()
    note.setText(text)
    NB_NOTES.append((note, near))
    return note


def nb_place_notes():
    for note, near in NB_NOTES:
        if near is not None:
            note.setPosition(near.position() + hou.Vector2(2.0, -0.5))
        note.setSize(hou.Vector2(5.0, 1.6))


def nb_connect(node, input_name, source, output=0):
    """Connect by input name (VOP networks); report instead of failing."""
    try:
        node.setNamedInput(input_name, source, output)
        return True
    except hou.Error as exc:
        NB_WARNINGS.append("%s: could not connect '%s' (%s)" % (node.path(), input_name, exc))
        return False


def nb_meta(node, comment, data):
    node.setComment(comment)
    node.setGenericFlag(hou.nodeFlag.DisplayComment, True)
    node.setUserData("nodebridge", data)

def build():
    img = hou.node("/img")
    net = nb_create(img, "img", "nb_scene_compositor")

    # Render Layers: RENDER_LAYER [APPROXIMATE]
    render_layers = nb_create(net, "file", "render_layers")
    nb_set(render_layers, "filename1", "$HIP/render/$F4.exr")
    nb_note(net, 'Set this File COP to the rendered image sequence.', render_layers)

    # Bloom: GLARE [UNSUPPORTED]
    bloom = nb_create(net, "null", "bloom")
    bloom.setInput(0, render_layers)
    nb_note(net, "'Bloom' (GLARE) was not translated: No NodeBridge translation is implemented for this operation on this target.", bloom)

    # Grade: COLOR_BALANCE [APPROXIMATE]
    grade = nb_create(net, "colorcorrect", "grade")
    nb_set(grade, "lift", (0.98, 1.0, 1.04))
    nb_set(grade, "gamma", (1.0, 1.0, 1.0))
    nb_set(grade, "gain", (1.05, 1.0, 0.92))
    grade.setInput(0, bloom)

    # Vignette: VIGNETTE [UNSUPPORTED]
    vignette = nb_create(net, "null", "vignette")
    vignette.setInput(0, grade)
    nb_note(net, "'Vignette' (VIGNETTE) was not translated: No NodeBridge translation is implemented for this operation on this target.", vignette)

    # Composite: COMPOSITE_OUTPUT [EQUIVALENT]
    composite = nb_create(net, "null", "composite")
    composite.setInput(0, vignette)
    composite.setDisplayFlag(True)
    net.layoutChildren()
    nb_place_notes()
    return net

net = build()
print("NodeBridge: created", net.path())
for nb_warning in NB_WARNINGS:
    print("NodeBridge warning:", nb_warning)
