"""NodeBridge: generated Unreal Editor Python.

Source:  Compositor / Scene Compositor (Blender 4.2.23 LTS)
Target:  Unreal Engine 5 (Post Process Volume)
Translation: 0 exact, 2 equivalent, 3 approximate, 0 unsupported
Generated by NodeBridge 0.3.0.

Run inside the Unreal Editor with the Python Editor Script Plugin enabled:
Window > Output Log > Python command line, or Tools > Execute Python Script.
New assets are created under ASSET_PATH; existing assets are never overwritten.
"""
import unreal

ASSET_PATH = "/Game/NodeBridge"
NB_WARNINGS = []


def nb_unique_asset_name(path, name):
    candidate, index = name, 1
    while unreal.EditorAssetLibrary.does_asset_exist("%s/%s" % (path, candidate)):
        index += 1
        candidate = "%s_%d" % (name, index)
    return candidate


def nb_create_asset(name, path, asset_class, factory):
    """Create a new asset; never overwrites an existing one."""
    unreal.EditorAssetLibrary.make_directory(path)
    name = nb_unique_asset_name(path, name)
    asset = unreal.AssetToolsHelpers.get_asset_tools().create_asset(name, path, asset_class, factory)
    if asset is None:
        raise RuntimeError("NodeBridge could not create %s/%s" % (path, name))
    return asset


def nb_class(name):
    cls = getattr(unreal, name, None)
    if cls is None:
        NB_WARNINGS.append("unreal.%s is not available in this Unreal version" % name)
    return cls


def nb_enum(enum_name, *candidates):
    enum = getattr(unreal, enum_name, None)
    for candidate in candidates:
        if enum is not None and hasattr(enum, candidate):
            return getattr(enum, candidate)
    NB_WARNINGS.append("unreal.%s has none of %s" % (enum_name, ", ".join(candidates)))
    return None


def nb_prop(obj, name, value):
    """set_editor_property with a warning instead of an exception."""
    if obj is None or value is None:
        return False
    try:
        obj.set_editor_property(name, value)
        return True
    except Exception as exc:
        NB_WARNINGS.append("%s.%s: %s" % (type(obj).__name__, name, exc))
        return False

def nb_setting(settings, name, value):
    """Set a post-process value and enable its override flag."""
    if nb_prop(settings, name, value):
        nb_prop(settings, "override_" + name, True)

def build():
    actors = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    volume = actors.spawn_actor_from_class(unreal.PostProcessVolume, unreal.Vector(0.0, 0.0, 0.0))
    volume.set_actor_label("NB_SceneCompositor")
    nb_prop(volume, "unbound", True)
    settings = volume.get_editor_property("settings")
    # Render Layers: RENDER_LAYER [EQUIVALENT]
    # Bloom: GLARE [APPROXIMATE]
    nb_setting(settings, "bloom_intensity", 1.0)
    nb_setting(settings, "bloom_threshold", 0.8)
    # Grade: COLOR_BALANCE [APPROXIMATE]
    nb_setting(settings, "color_gain", unreal.Vector4(1.05, 1.0, 0.92, 1.0))
    nb_setting(settings, "color_gamma", unreal.Vector4(1.0, 1.0, 1.0, 1.0))
    nb_setting(settings, "color_offset", unreal.Vector4(-0.02, 0.0, 0.04, 0.0))
    # Vignette: VIGNETTE [APPROXIMATE]
    nb_setting(settings, "vignette_intensity", 0.6)
    # Composite: COMPOSITE_OUTPUT [EQUIVALENT]
    volume.set_editor_property("settings", settings)
    return volume

volume = build()
print("NodeBridge: created post process volume", volume.get_actor_label())
for nb_warning in NB_WARNINGS:
    unreal.log_warning("NodeBridge: " + nb_warning)
