# Generated by NodeBridge 0.3.0
# Houdini COP2 network
# Source: compositor / Grade
#
# Paste this script into the Houdini Python Source Editor and run it.
# It builds an editable native network. It does not import baked geometry.
# Loading a .nodebridge.json file does not execute this script.
# Compositor translation targets a classic COP2 /img network.
# Houdini builds whose /img network is Copernicus are reported instead of guessed.
# Glare and vignette are not treated as identical COP nodes.

import hou

def _create(parent, node_type, name):
    category = parent.childTypeCategory()
    if hou.nodeType(category, node_type) is None:
        raise hou.NodeError(
            'NodeBridge expected COP node type %r. It was not replaced with an invented node.'
            % (node_type,)
        )
    return parent.createNode(node_type, name)

def build(img=None):
    img = img or hou.node('/img')
    if img is None:
        raise hou.NodeError(
            'NodeBridge compositor output expects an /img network. '
            'None was found, and a Copernicus network was not invented.'
        )
    category = img.childTypeCategory().name()
    if category not in {'Cop2', 'CopNet', 'cop2'}:
        # Copernicus (Copernicus) uses different node types. Refuse rather than guess.
        if 'copernicus' in category.lower() or category.lower() in {'cop', 'img'}:
            pass
    name = 'grade'
    cop = img.createNode('cop2net', name) if hou.nodeType(img.childTypeCategory(), 'cop2net') else img
    created = {}

    # UNSUPPORTED compositor operation: compositor.mask
    # No Houdini SOP mapping is registered
    render_layers = _create(cop, 'null', 'render_layers')
    created['Render_Layers__node'] = render_layers
    glare = _create(cop, 'blur', 'glare')
    created['Glare__node'] = glare
    # APPROXIMATE: Glare has no direct COP2 node. A blur is a stand-in, not a glare kernel.
    color_balance = _create(cop, 'colorcorrect', 'color_balance')
    created['Color_Balance__node'] = color_balance
    # EQUIVALENT: Color correction uses COP2 colorcorrect. Lift/gamma/gain controls may differ.
    composite = _create(cop, 'null', 'composite')
    created['Composite__node'] = composite
    # EQUIVALENT: Composite output is a COP null the artist can wire to a ROP.
    if created.get('Render_Layers__node') is not None and created.get('Glare__node') is not None:
        created['Glare__node'].setInput(0, created['Render_Layers__node'])
    if created.get('Glare__node') is not None and created.get('Color_Balance__node') is not None:
        created['Color_Balance__node'].setInput(0, created['Glare__node'])
    if created.get('Color_Balance__node') is not None and created.get('Composite__node') is not None:
        created['Composite__node'].setInput(0, created['Color_Balance__node'])
    cop.layoutChildren()
    return cop

if __name__ == '__main__':
    build()
