# Generated by NodeBridge 0.3.0
# Unreal Editor Python — compositor
# Source: compositor / Grade
#
# UNSUPPORTED as a native graph.
# Unreal's public Editor Python API does not construct a Blender-style
# compositor (render layer, glare, vignette, composite output).
# NodeBridge will not invent a post-process material graph for these nodes.
#
# Operations in the source graph:
# - compositor.color_correct (CompositorNodeColorBalance)
# - compositor.output (CompositorNodeComposite)
# - compositor.mask (CompositorNodeEllipseMask)
# - compositor.glare (CompositorNodeGlare)
# - compositor.input (CompositorNodeRLayers)
#
# Nothing was created.
def build():
    raise RuntimeError(
        'NodeBridge has no Unreal compositor backend for this graph. '
        'See the comments above. No assets were created.'
    )
