"""Houdini SOP backend.

Produces an editable SOP construction plan. Generated hou scripts are text;
they are never executed by loading IR.
"""

from __future__ import annotations

from nodebridge.backends.base import GraphFragment, TargetConnectionSpec, TargetNodeSpec
from nodebridge.core.capabilities import CapabilitySet
from nodebridge.core.diagnostics import TranslationStatus
from nodebridge.core.graph import IRGraph
from nodebridge.core.metadata import SourceMapping
from nodebridge.core.node import IRNode
from nodebridge.hosts.assemble import assemble_native
from nodebridge.hosts.contract import Implementation, LoweringFragment
from nodebridge.hosts.houdini.capabilities import houdini_capabilities
from nodebridge.hosts.houdini.mappings import HOUDINI_RECIPES, PRIMITIVE_BACKEND_TYPES
from nodebridge.hosts.native import NativeGraph
from nodebridge.hosts.recipes import unsupported_fragment
from nodebridge.ir.versioning import PACKAGE_VERSION


class HoudiniBackend:
    """Translate IR geometry graphs into Houdini SOP networks."""

    name = "houdini"

    def __init__(self) -> None:
        self.capabilities: CapabilitySet = houdini_capabilities()

    def implementation_for(self, operation: str) -> Implementation:
        recipe = HOUDINI_RECIPES.get(operation)
        if recipe is None:
            return Implementation(
                operation=operation,
                fidelity=TranslationStatus.UNSUPPORTED,
                available=False,
                note="No Houdini SOP mapping is registered",
            )
        return recipe.implementation()

    def lower_node(self, node: IRNode) -> LoweringFragment:
        recipe = HOUDINI_RECIPES.get(node.operation)
        if recipe is None:
            return unsupported_fragment(node, note="No Houdini SOP mapping is registered")
        fragment = recipe.apply(node)
        if node.operation == "geometry.primitive" and fragment.nodes:
            kind = "cube"
            if "primitive" in node.parameters:
                kind = str(node.parameters["primitive"].value)
            fragment.nodes[0].type = PRIMITIVE_BACKEND_TYPES.get(kind, "box")
            fragment.recipe = fragment.nodes[0].type
        return fragment

    def translate_node(self, node: IRNode) -> GraphFragment:
        fragment = self.lower_node(node)
        return GraphFragment(
            nodes=[
                TargetNodeSpec(id=item.id, kind=item.type, parameters=dict(item.parameters))
                for item in fragment.nodes
            ],
            connections=[
                TargetConnectionSpec(
                    source_node=link.source_node,
                    source_socket=link.source_socket,
                    target_node=link.target_node,
                    target_socket=link.target_socket,
                )
                for link in fragment.links
            ],
            status=fragment.fidelity,
            mapping=SourceMapping(
                ir_node_id=node.id,
                target_nodes=[item.id for item in fragment.nodes],
            ),
        )

    def build(self, graph: IRGraph) -> NativeGraph:
        native, _report = assemble_native(graph, self, host_id="houdini", system="sop")
        return native

    def generate(self, graph: IRGraph) -> str:
        return emit_houdini_script(self.build(graph))


def emit_houdini_script(native: NativeGraph) -> str:
    """Deterministic hou Python. Execute only inside Houdini."""
    lines = [
        f"# Generated by NodeBridge {PACKAGE_VERSION}",
        "# Execute inside Houdini. Loading a .nodebridge.json file does not run this.",
        "import hou",
        "",
        "def build(parent=None):",
        "    parent = parent or hou.node('/obj')",
        f"    geo = parent.createNode('geo', {_safe_hou_name(native.name)!r})",
        "    for child in geo.children():",
        "        child.destroy()",
        "    created = {}",
    ]
    for node in native.nodes:
        hou_type = node.type.split("::")[0]
        lines.append(f"    node = geo.createNode({hou_type!r}, {_safe_hou_name(node.id)!r})")
        for key, value in node.parameters.items():
            if key in {"role", "label", "snippet"}:
                continue
            lines.append(f"    if node.parm({key!r}) is not None:")
            lines.append(f"        node.parm({key!r}).set({value!r})")
        snippet = node.parameters.get("snippet")
        if snippet:
            lines.append("    if node.parm('snippet') is not None:")
            lines.append(f"        node.parm('snippet').set({snippet!r})")
        lines.append(f"    created[{node.id!r}] = node")
    for link in native.links:
        lines.append(
            f"    created[{link.target_node!r}].setInput("
            f"{_input_index(link.target_socket)}, created[{link.source_node!r}])"
        )
    lines.append("    geo.layoutChildren()")
    lines.append("    return geo")
    lines.append("")
    lines.append("if __name__ == '__main__':")
    lines.append("    build()")
    lines.append("")
    return "\n".join(lines)


def _safe_hou_name(value: str) -> str:
    cleaned = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in value)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"n_{cleaned}"
    return cleaned[:64]


def _input_index(socket: str) -> int:
    digits = "".join(ch for ch in socket if ch.isdigit())
    return int(digits) if digits else 0
