"""Unreal PCG backend.

Primary output is a construction plan. Generated Unreal Python uses the
documented UE 5.7 experimental API (``add_node_of_type``, ``add_edge``)
and is not executed by IR load. Runtime application requires the editor.
"""

from __future__ import annotations

from nodebridge.backends.base import GraphFragment, TargetConnectionSpec, TargetNodeSpec
from nodebridge.core.capabilities import CapabilitySet
from nodebridge.core.diagnostics import TranslationStatus
from nodebridge.core.graph import IRGraph
from nodebridge.core.metadata import SourceMapping
from nodebridge.core.node import IRNode
from nodebridge.hosts.assemble import assemble_native
from nodebridge.hosts.contract import Implementation, LoweringFragment
from nodebridge.hosts.native import NativeGraph
from nodebridge.hosts.recipes import unsupported_fragment
from nodebridge.hosts.unreal.capabilities import unreal_capabilities
from nodebridge.hosts.unreal.mappings import SETTINGS_CLASSES, UNREAL_RECIPES
from nodebridge.ir.versioning import PACKAGE_VERSION


class UnrealBackend:
    """Translate IR graphs into Unreal PCG construction plans."""

    name = "unreal"

    def __init__(self) -> None:
        self.capabilities: CapabilitySet = unreal_capabilities()

    def implementation_for(self, operation: str) -> Implementation:
        recipe = UNREAL_RECIPES.get(operation)
        if recipe is None:
            return Implementation(
                operation=operation,
                fidelity=TranslationStatus.UNSUPPORTED,
                available=False,
                note=(
                    "No Unreal PCG mapping is registered. Math/vector ops are "
                    "not first-class PCG nodes in the current Python API."
                ),
            )
        return recipe.implementation()

    def lower_node(self, node: IRNode) -> LoweringFragment:
        recipe = UNREAL_RECIPES.get(node.operation)
        if recipe is None:
            return unsupported_fragment(
                node,
                note=(
                    "No Unreal PCG mapping is registered. Do not invent a "
                    "Material or Blueprint substitute silently."
                ),
            )
        return recipe.apply(node)

    def translate_node(self, node: IRNode) -> GraphFragment:
        fragment = self.lower_node(node)
        return GraphFragment(
            nodes=[
                TargetNodeSpec(id=item.id, kind=item.type, parameters=dict(item.parameters))
                for item in fragment.nodes
            ],
            connections=[
                TargetConnectionSpec(
                    source_node=link.source_node,
                    source_socket=link.source_socket,
                    target_node=link.target_node,
                    target_socket=link.target_socket,
                )
                for link in fragment.links
            ],
            status=fragment.fidelity,
            mapping=SourceMapping(
                ir_node_id=node.id,
                target_nodes=[item.id for item in fragment.nodes],
            ),
        )

    def build(self, graph: IRGraph) -> NativeGraph:
        native, _report = assemble_native(graph, self, host_id="unreal", system="pcg")
        native.metadata["api"] = "experimental-ue5.7"
        native.metadata["runtime"] = "editor-only"
        return native

    def generate(self, graph: IRGraph) -> str:
        return emit_unreal_script(self.build(graph))


def emit_unreal_script(native: NativeGraph) -> str:
    """UE 5.7+ experimental PCG Python. Editor-only; not executed by IR load."""
    lines = [
        f"# Generated by NodeBridge {PACKAGE_VERSION}",
        "# Unreal Engine 5.7+ experimental PCG Python API.",
        "# Requires the Unreal editor with the PCG plugin enabled.",
        "# add_node_of_type / add_edge are editor-only and version-sensitive.",
        "# add_edge silently no-ops on wrong pin labels — inspect pins first.",
        "# Loading a .nodebridge.json file does not execute this script.",
        "import unreal",
        "",
        "def build(graph_path: str):",
        "    graph = unreal.EditorAssetLibrary.load_asset(graph_path)",
        "    created = {}",
        "    input_node = graph.get_input_node()",
        "    output_node = graph.get_output_node()",
        "    created['input'] = input_node",
        "    created['output'] = output_node",
    ]
    x = 200
    for node in native.nodes:
        if node.type in {"Input", "Output", "PCGGraphInput", "PCGGraphOutput"}:
            key = "input" if "input" in node.type.lower() or node.type == "Input" else "output"
            lines.append(f"    created[{node.id!r}] = created[{key!r}]")
            continue
        settings = SETTINGS_CLASSES.get(node.type)
        if settings is None:
            lines.append(f"    # TODO: no documented settings class for {node.type!r}")
            lines.append(f"    created[{node.id!r}] = None")
            continue
        lines.append(f"    node, settings = graph.add_node_of_type({settings})")
        lines.append(f"    node.set_node_position({x}, 0)")
        for key, value in node.parameters.items():
            lines.append(f"    if settings is not None:")
            lines.append(f"        try:")
            lines.append(f"            settings.set_editor_property({key!r}, {value!r})")
            lines.append(f"        except Exception:")
            lines.append(f"            pass")
        lines.append(f"    created[{node.id!r}] = node")
        x += 220
    for link in native.links:
        lines.append(
            f"    if created.get({link.source_node!r}) is not None and "
            f"created.get({link.target_node!r}) is not None:"
        )
        lines.append(
            f"        graph.add_edge(created[{link.source_node!r}], {link.source_socket!r}, "
            f"created[{link.target_node!r}], {link.target_socket!r})"
        )
    lines.append("    return graph")
    lines.append("")
    return "\n".join(lines)
