"""Unreal Editor Python for materials and an honest compositor report.

Material expressions use ``MaterialEditingLibrary``, which is part of the
editor Python API. Compositor graphs are not emitted as fake post-process
node networks: the public Python API does not construct a Blender-style
compositor, and NodeBridge says so.
"""

from __future__ import annotations

from nodebridge.common.names import sanitize_identifier
from nodebridge.core.graph import IRGraph
from nodebridge.ir.versioning import PACKAGE_VERSION

_EXPRESSIONS = {
    "shader.principled_surface": "unreal.MaterialExpressionMakeMaterialAttributes",
    "shader.output": None,
    "procedural.noise": "unreal.MaterialExpressionNoise",
    "procedural.voronoi": "unreal.MaterialExpressionNoise",
    "color.ramp": "unreal.MaterialExpressionLinearInterpolate",
    "color.mix": "unreal.MaterialExpressionLinearInterpolate",
    "math.add": "unreal.MaterialExpressionAdd",
    "math.subtract": "unreal.MaterialExpressionSubtract",
    "math.multiply": "unreal.MaterialExpressionMultiply",
    "math.divide": "unreal.MaterialExpressionDivide",
    "texture.sample": "unreal.MaterialExpressionTextureSample",
    "shader.texcoord": "unreal.MaterialExpressionTextureCoordinate",
    "shader.normal": "unreal.MaterialExpressionNormalMap",
    "graph.input": "unreal.MaterialExpressionScalarParameter",
    "graph.output": None,
}


def emit_unreal_material(graph: IRGraph) -> str:
    """Editor Python that creates a Material asset and expression graph."""
    asset = sanitize_identifier(graph.name, fallback="material")
    lines = [
        f"# Generated by NodeBridge {PACKAGE_VERSION}",
        "# Unreal Editor Python — Material",
        f"# Source: shader / {graph.name}",
        "#",
        "# Requires the Unreal Editor Python Script Plugin.",
        "# This creates a Material asset under /Game/NodeBridge.",
        "# Principled BSDF is approximated with material attributes.",
        "# Noise will not match Blender's Noise Texture.",
        "# Run this inside the Unreal Editor, not an external Python.",
        "import unreal",
        "",
        "def build(asset_name=None, package_path='/Game/NodeBridge'):",
        f"    asset_name = asset_name or {asset!r}",
        "    tools = unreal.AssetToolsHelpers.get_asset_tools()",
        "    material = tools.create_asset(",
        "        asset_name,",
        "        package_path,",
        "        unreal.Material,",
        "        unreal.MaterialFactoryNew(),",
        "    )",
        "    library = unreal.MaterialEditingLibrary",
        "    created = {}",
        "    x = -800",
        "",
    ]
    try:
        order = graph.topological_order()
    except ValueError:
        order = sorted(graph.nodes)
    for node_id in order:
        node = graph.nodes[node_id]
        expression = _EXPRESSIONS.get(node.operation)
        if node.operation in {"shader.output", "graph.output"}:
            lines.append(f"    created[{node.id!r}] = None  # material output is the root node")
            continue
        if expression is None:
            lines.append(f"    # UNSUPPORTED material operation: {node.operation}")
            lines.append(f"    created[{node.id!r}] = None")
            continue
        if node.operation == "procedural.voronoi":
            lines.append("    # APPROXIMATE: Blender Voronoi is emitted as MaterialExpressionNoise.")
        if node.operation == "color.ramp":
            lines.append("    # APPROXIMATE: a color ramp is a lerp, not a Blender color ramp.")
        if node.operation == "shader.principled_surface":
            lines.append("    # EQUIVALENT: material attributes stand in for Principled BSDF.")
        lines.append(f"    created[{node.id!r}] = library.create_material_expression(")
        lines.append(f"        material, {expression}, x, 0")
        lines.append("    )")
        lines.append("    x += 220")
    lines.append("    # Connections use output and input names. Wrong names raise rather than being ignored.")
    for connection in graph.connections:
        source = graph.nodes.get(connection.source_node)
        target = graph.nodes.get(connection.target_node)
        if source is None or target is None:
            continue
        if target.operation == "shader.output":
            prop = _material_property(connection.target_socket, target)
            lines.append(f"    if created.get({connection.source_node!r}) is not None:")
            lines.append("        library.connect_material_property(")
            lines.append(f"            created[{connection.source_node!r}], '', {prop}")
            lines.append("        )")
            continue
        lines.append(
            f"    if created.get({connection.source_node!r}) is not None and created.get({connection.target_node!r}) is not None:"
        )
        lines.append("        library.connect_material_expressions(")
        lines.append(f"            created[{connection.source_node!r}], '',")
        lines.append(f"            created[{connection.target_node!r}], ''")
        lines.append("        )")
    lines += [
        "    library.recompile_material(material)",
        "    unreal.EditorAssetLibrary.save_loaded_asset(material)",
        "    return material",
        "",
        "if __name__ == '__main__':",
        "    build()",
        "",
    ]
    return "\n".join(lines)


def emit_unreal_compositor(graph: IRGraph) -> str:
    """Explain that a Blender compositor is not built as a fake Unreal graph."""
    lines = [
        f"# Generated by NodeBridge {PACKAGE_VERSION}",
        "# Unreal Editor Python — compositor",
        f"# Source: compositor / {graph.name}",
        "#",
        "# UNSUPPORTED as a native graph.",
        "# Unreal's public Editor Python API does not construct a Blender-style",
        "# compositor (render layer, glare, vignette, composite output).",
        "# NodeBridge will not invent a post-process material graph for these nodes.",
        "#",
        "# Operations in the source graph:",
    ]
    for node in graph.nodes.values():
        lines.append(f"# - {node.operation} ({node.metadata.provenance.original_type or 'unspecified'})")
    lines += [
        "#",
        "# Nothing was created.",
        "def build():",
        "    raise RuntimeError(",
        "        'NodeBridge has no Unreal compositor backend for this graph. '",
        "        'See the comments above. No assets were created.'",
        "    )",
        "",
    ]
    return "\n".join(lines)


def _material_property(socket_id: str, node: object) -> str:
    del socket_id
    return "unreal.MaterialProperty.MP_BASE_COLOR"
