# Generated by NodeBridge 0.3.0
# Houdini MaterialX material
# Source: shader / Facade
#
# Paste this script into the Houdini Python Source Editor and run it.
# It builds an editable native network. It does not import baked geometry.
# Loading a .nodebridge.json file does not execute this script.
# This builds a Material Builder under /mat.
# MaterialX node types vary by Houdini version. Missing types raise.
# Principled BSDF is lowered to mtlxstandard_surface (equivalent, not identical).
# Noise will not match Blender's Noise Texture.

import hou

def _create(parent, node_type, name):
    category = parent.childTypeCategory()
    if hou.nodeType(category, node_type) is None:
        raise hou.NodeError(
            'NodeBridge expected %r in %s. No substitute node was invented.'
            % (node_type, parent.path())
        )
    return parent.createNode(node_type, name)

def build(mat=None):
    mat = mat or hou.node('/mat')
    if mat is None:
        mat = hou.node('/').createNode('matnet', 'mat')
    builder = _create(mat, 'materialbuilder', 'facade')
    for child in list(builder.children()):
        if child.type().name() not in {'subinput', 'suboutput'}:
            child.destroy()
    created = {}

    noise = _create(builder, 'mtlxnoise3d', 'noise')
    created['Noise__node'] = noise
    # MaterialX noise is not Blender's Noise Texture. The pattern will not match.
    bump = _create(builder, 'mtlxnormalmap', 'bump')
    created['Bump__node'] = bump
    # A normal map is not Blender's Bump node.
    color_ramp = _create(builder, 'mtlxmix', 'color_ramp')
    created['Color_Ramp__node'] = color_ramp
    # A color ramp is not reproduced. A mix stands in for a two-stop blend.
    principled = _create(builder, 'mtlxstandard_surface', 'principled')
    created['Principled__node'] = principled
    # MaterialX Standard Surface approximates Principled BSDF. Closures are not numerically identical.
    material_output = _create(builder, 'mtlxsurfacematerial', 'material_output')
    created['Material_Output__node'] = material_output
    # The material output is a MaterialX surface material inside a Material Builder.
    if created.get('Noise__node') is not None and created.get('Color_Ramp__node') is not None:
        created['Color_Ramp__node'].setInput(0, created['Noise__node'])
    if created.get('Color_Ramp__node') is not None and created.get('Principled__node') is not None:
        created['Principled__node'].setInput(0, created['Color_Ramp__node'])
    if created.get('Noise__node') is not None and created.get('Principled__node') is not None:
        created['Principled__node'].setInput(0, created['Noise__node'])
    if created.get('Noise__node') is not None and created.get('Bump__node') is not None:
        created['Bump__node'].setInput(0, created['Noise__node'])
    if created.get('Bump__node') is not None and created.get('Principled__node') is not None:
        created['Principled__node'].setInput(0, created['Bump__node'])
    if created.get('Principled__node') is not None and created.get('Material_Output__node') is not None:
        created['Material_Output__node'].setInput(0, created['Principled__node'])
    surface = created.get('surface')
    # Connect the last shader node to a MaterialX surface material when that type exists.
    if hou.nodeType(builder.childTypeCategory(), 'mtlxsurfacematerial') is not None:
        collect = _create(builder, 'mtlxsurfacematerial', 'surface_material')
        shaders = [node for node in created.values() if node.type().name() == 'mtlxstandard_surface']
        if shaders:
            collect.setInput(0, shaders[-1])
    for node in created.values():
        node.moveToGoodPosition()
    builder.layoutChildren()
    return builder

if __name__ == '__main__':
    build()
