# Generated by NodeBridge 0.3.0
# Unreal Editor Python — Material
# Source: shader / Facade
#
# Requires the Unreal Editor Python Script Plugin.
# This creates a Material asset under /Game/NodeBridge.
# Principled BSDF is approximated with material attributes.
# Noise will not match Blender's Noise Texture.
# Run this inside the Unreal Editor, not an external Python.
import unreal

def build(asset_name=None, package_path='/Game/NodeBridge'):
    asset_name = asset_name or 'facade'
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    material = tools.create_asset(
        asset_name,
        package_path,
        unreal.Material,
        unreal.MaterialFactoryNew(),
    )
    library = unreal.MaterialEditingLibrary
    created = {}
    x = -800

    created['Noise'] = library.create_material_expression(
        material, unreal.MaterialExpressionNoise, x, 0
    )
    x += 220
    created['Bump'] = library.create_material_expression(
        material, unreal.MaterialExpressionNormalMap, x, 0
    )
    x += 220
    # APPROXIMATE: a color ramp is a lerp, not a Blender color ramp.
    created['Color_Ramp'] = library.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, x, 0
    )
    x += 220
    # EQUIVALENT: material attributes stand in for Principled BSDF.
    created['Principled'] = library.create_material_expression(
        material, unreal.MaterialExpressionMakeMaterialAttributes, x, 0
    )
    x += 220
    created['Material_Output'] = None  # material output is the root node
    # Connections use output and input names. Wrong names raise rather than being ignored.
    if created.get('Noise') is not None and created.get('Color_Ramp') is not None:
        library.connect_material_expressions(
            created['Noise'], '',
            created['Color_Ramp'], ''
        )
    if created.get('Color_Ramp') is not None and created.get('Principled') is not None:
        library.connect_material_expressions(
            created['Color_Ramp'], '',
            created['Principled'], ''
        )
    if created.get('Noise') is not None and created.get('Principled') is not None:
        library.connect_material_expressions(
            created['Noise'], '',
            created['Principled'], ''
        )
    if created.get('Noise') is not None and created.get('Bump') is not None:
        library.connect_material_expressions(
            created['Noise'], '',
            created['Bump'], ''
        )
    if created.get('Bump') is not None and created.get('Principled') is not None:
        library.connect_material_expressions(
            created['Bump'], '',
            created['Principled'], ''
        )
    if created.get('Principled') is not None:
        library.connect_material_property(
            created['Principled'], '', unreal.MaterialProperty.MP_BASE_COLOR
        )
    library.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
    return material

if __name__ == '__main__':
    build()
