"""NodeBridge: generated Unreal Editor Python.

Source:  Geometry Nodes / ScatterRocks (Blender 4.2.23 LTS)
Target:  Unreal Engine 5 (PCG graph)
Translation: 4 exact, 9 equivalent, 8 approximate, 0 unsupported
Generated by NodeBridge 0.3.0.

Run inside the Unreal Editor with the Python Editor Script Plugin enabled:
Window > Output Log > Python command line, or Tools > Execute Python Script.
Requires the PCG plugin. The PCG Python API is experimental (UE 5.4+); anything
this editor version does not expose is listed as a NodeBridge warning in the log.
New assets are created under ASSET_PATH; existing assets are never overwritten.
"""
import unreal

ASSET_PATH = "/Game/NodeBridge"
SPAWN_PCG_VOLUME = False  # True: also place a PCG Volume using the new graph

# Controls (Blender group inputs, Blender units). Edit and re-run to rebuild the graph.
DENSITY = 4.0  # Density
SEED = 7  # Seed
SCALE_MIN = 0.6  # Scale Min
SCALE_MAX = 1.4  # Scale Max
COVERAGE = 0.45  # Coverage
NB_WARNINGS = []


def nb_unique_asset_name(path, name):
    candidate, index = name, 1
    while unreal.EditorAssetLibrary.does_asset_exist("%s/%s" % (path, candidate)):
        index += 1
        candidate = "%s_%d" % (name, index)
    return candidate


def nb_create_asset(name, path, asset_class, factory):
    """Create a new asset; never overwrites an existing one."""
    unreal.EditorAssetLibrary.make_directory(path)
    name = nb_unique_asset_name(path, name)
    asset = unreal.AssetToolsHelpers.get_asset_tools().create_asset(name, path, asset_class, factory)
    if asset is None:
        raise RuntimeError("NodeBridge could not create %s/%s" % (path, name))
    return asset


def nb_class(name):
    cls = getattr(unreal, name, None)
    if cls is None:
        NB_WARNINGS.append("unreal.%s is not available in this Unreal version" % name)
    return cls


def nb_enum(enum_name, *candidates):
    enum = getattr(unreal, enum_name, None)
    for candidate in candidates:
        if enum is not None and hasattr(enum, candidate):
            return getattr(enum, candidate)
    NB_WARNINGS.append("unreal.%s has none of %s" % (enum_name, ", ".join(candidates)))
    return None


def nb_prop(obj, name, value):
    """set_editor_property with a warning instead of an exception."""
    if obj is None or value is None:
        return False
    try:
        obj.set_editor_property(name, value)
        return True
    except Exception as exc:
        NB_WARNINGS.append("%s.%s: %s" % (type(obj).__name__, name, exc))
        return False

def nb_pcg_node(graph, settings_class_name, x, y):
    settings_class = nb_class(settings_class_name)
    if settings_class is None:
        return None, None
    node, settings = graph.add_node_of_type(settings_class)
    try:
        node.set_node_position(x, y)
    except Exception:
        pass
    return node, settings


def nb_edge(graph, source, source_pins, target, target_pins):
    """Connect two PCG nodes, trying known pin labels across UE versions."""
    if source is None or target is None:
        return False
    for source_pin in source_pins:
        for target_pin in target_pins:
            if graph.add_edge(source, source_pin, target, target_pin) is not None:
                return True
    NB_WARNINGS.append("could not connect %s -> %s (pins %s / %s)" % (source_pins, target_pins, source_pins, target_pins))
    return False


def nb_spawner_mesh(settings, mesh_path, material=None):
    """Point a Static Mesh Spawner at one mesh (UE 5.2+ descriptor API, 5.0/5.1 fallback)."""
    mesh = unreal.EditorAssetLibrary.load_asset(mesh_path)
    if mesh is None:
        NB_WARNINGS.append("static mesh %s not found; assign one on the Static Mesh Spawner" % mesh_path)
        return False
    try:
        settings.set_mesh_selector_type(unreal.PCGMeshSelectorWeighted)
    except Exception:
        nb_prop(settings, "mesh_selector_type", getattr(unreal, "PCGMeshSelectorWeighted", None))
    selector = settings.get_editor_property("mesh_selector_parameters")
    entry = unreal.PCGMeshSelectorWeightedEntry()
    try:
        descriptor = entry.get_editor_property("descriptor")
        descriptor.set_editor_property("static_mesh", mesh)
        if material is not None:
            descriptor.set_editor_property("override_materials", [material])
        entry.set_editor_property("descriptor", descriptor)
    except Exception:
        nb_prop(entry, "mesh", mesh)
    nb_prop(entry, "weight", 1)
    return nb_prop(selector, "mesh_entries", [entry])
MEL = unreal.MaterialEditingLibrary


def nb_expression(material, class_name, x, y):
    cls = nb_class(class_name)
    if cls is None:
        return None
    return MEL.create_material_expression(material, cls, x, y)


def nb_link(source, source_output, target, target_input):
    if source is None or target is None:
        return False
    if not MEL.connect_material_expressions(source, source_output, target, target_input):
        NB_WARNINGS.append("could not connect %s.%s -> %s.%s" % (type(source).__name__, source_output, type(target).__name__, target_input))
        return False
    return True


def nb_output(source, source_output, material_property):
    if source is None or material_property is None:
        return False
    if not MEL.connect_material_property(source, source_output, material_property):
        NB_WARNINGS.append("could not connect %s to %s" % (type(source).__name__, material_property))
        return False
    return True

def build_materials():
    created = {}

    def build_material_procedural_rock():
        """Material 'ProceduralRock' as an Unreal Material asset."""
        material = nb_create_asset("M_ProceduralRock", ASSET_PATH, unreal.Material, unreal.MaterialFactoryNew())
        # Principled BSDF: SHADER_BSDF -> material attributes
        # Rock Colors: COLOR_RAMP [EXACT]
        # Rock Noise: NOISE [APPROXIMATE]
        rock_noise = nb_expression(material, "MaterialExpressionNoise", -660, 140)
        # Mapping: MAPPING [EXACT]
        mapping_scale = nb_expression(material, "MaterialExpressionMultiply", -920, 280)
        # Texture Coordinate Object: FIELD_INPUT [EQUIVALENT]
        texture_coordinate_object = nb_expression(material, "MaterialExpressionLocalPosition", -1180, 420)
        texture_coordinate_object_to_blender_meters = nb_expression(material, "MaterialExpressionMultiply", -1440, 560)
        nb_link(texture_coordinate_object, '', texture_coordinate_object_to_blender_meters, 'A')
        constant3vector = nb_expression(material, "MaterialExpressionConstant3Vector", -1700, 700)
        nb_prop(constant3vector, "constant", unreal.LinearColor(0.01, -0.01, 0.01, 1.0))
        nb_link(constant3vector, '', texture_coordinate_object_to_blender_meters, 'B')
        nb_link(texture_coordinate_object_to_blender_meters, '', mapping_scale, 'A')
        constant3vector_2 = nb_expression(material, "MaterialExpressionConstant3Vector", -400, 840)
        nb_prop(constant3vector_2, "constant", unreal.LinearColor(2.0, 2.0, 2.0, 1.0))
        nb_link(constant3vector_2, '', mapping_scale, 'B')
        nb_link(mapping_scale, '', rock_noise, 'Position')
        nb_prop(rock_noise, "scale", 4.0)
        nb_prop(rock_noise, "levels", 9)
        nb_prop(rock_noise, "output_min", 0.0)
        nb_prop(rock_noise, "output_max", 1.0)
        nb_prop(rock_noise, "noise_function", nb_enum("NoiseFunction", "NOISEFUNCTION_GRADIENT_ALU", "GRADIENT_ALU"))
        constant3vector_3 = nb_expression(material, "MaterialExpressionConstant3Vector", -660, 980)
        nb_prop(constant3vector_3, "constant", unreal.LinearColor(0.08, 0.07, 0.06, 1.0))
        rock_colors_segment_1_shift = nb_expression(material, "MaterialExpressionSubtract", -920, 1120)
        nb_link(rock_noise, '', rock_colors_segment_1_shift, 'A')
        nb_prop(rock_colors_segment_1_shift, "const_b", 0.3)
        rock_colors_segment_1_scale = nb_expression(material, "MaterialExpressionMultiply", -1180, 1260)
        nb_link(rock_colors_segment_1_shift, '', rock_colors_segment_1_scale, 'A')
        nb_prop(rock_colors_segment_1_scale, "const_b", 5.0)
        rock_colors_segment_1_clamp = nb_expression(material, "MaterialExpressionSaturate", -1440, 1400)
        nb_link(rock_colors_segment_1_scale, '', rock_colors_segment_1_clamp, '')
        rock_colors_stop_1 = nb_expression(material, "MaterialExpressionLinearInterpolate", -1700, 1540)
        nb_link(constant3vector_3, '', rock_colors_stop_1, 'A')
        constant3vector_4 = nb_expression(material, "MaterialExpressionConstant3Vector", -400, 1680)
        nb_prop(constant3vector_4, "constant", unreal.LinearColor(0.25, 0.2, 0.15, 1.0))
        nb_link(constant3vector_4, '', rock_colors_stop_1, 'B')
        nb_link(rock_colors_segment_1_clamp, '', rock_colors_stop_1, 'Alpha')
        rock_colors_segment_2_shift = nb_expression(material, "MaterialExpressionSubtract", -660, 1820)
        nb_link(rock_noise, '', rock_colors_segment_2_shift, 'A')
        nb_prop(rock_colors_segment_2_shift, "const_b", 0.5)
        rock_colors_segment_2_scale = nb_expression(material, "MaterialExpressionMultiply", -920, 1960)
        nb_link(rock_colors_segment_2_shift, '', rock_colors_segment_2_scale, 'A')
        nb_prop(rock_colors_segment_2_scale, "const_b", 4.0)
        rock_colors_segment_2_clamp = nb_expression(material, "MaterialExpressionSaturate", -1180, 2100)
        nb_link(rock_colors_segment_2_scale, '', rock_colors_segment_2_clamp, '')
        rock_colors_stop_2 = nb_expression(material, "MaterialExpressionLinearInterpolate", -1440, 2240)
        nb_link(rock_colors_stop_1, '', rock_colors_stop_2, 'A')
        constant3vector_5 = nb_expression(material, "MaterialExpressionConstant3Vector", -1700, 2380)
        nb_prop(constant3vector_5, "constant", unreal.LinearColor(0.55, 0.5, 0.42, 1.0))
        nb_link(constant3vector_5, '', rock_colors_stop_2, 'B')
        nb_link(rock_colors_segment_2_clamp, '', rock_colors_stop_2, 'Alpha')
        nb_output(rock_colors_stop_2, '', unreal.MaterialProperty.MP_BASE_COLOR)
        constant = nb_expression(material, "MaterialExpressionConstant", -400, 2520)
        nb_prop(constant, "r", 0.0)
        nb_output(constant, '', unreal.MaterialProperty.MP_METALLIC)
        # Roughness Range: MAP_RANGE [EXACT]
        roughness_range_t_shift = nb_expression(material, "MaterialExpressionSubtract", -660, 2660)
        nb_link(rock_noise, '', roughness_range_t_shift, 'A')
        nb_prop(roughness_range_t_shift, "const_b", 0.0)
        roughness_range_t_scale = nb_expression(material, "MaterialExpressionMultiply", -920, 2800)
        nb_link(roughness_range_t_shift, '', roughness_range_t_scale, 'A')
        nb_prop(roughness_range_t_scale, "const_b", 1.0)
        roughness_range_t_clamp = nb_expression(material, "MaterialExpressionSaturate", -1180, 2940)
        nb_link(roughness_range_t_scale, '', roughness_range_t_clamp, '')
        roughness_range = nb_expression(material, "MaterialExpressionLinearInterpolate", -1440, 3080)
        nb_prop(roughness_range, "const_a", 0.45)
        param_roughness_scale = nb_expression(material, "MaterialExpressionScalarParameter", -1700, 3220)
        nb_prop(param_roughness_scale, "default_value", 0.9)
        nb_prop(param_roughness_scale, "parameter_name", 'Roughness Scale')
        nb_link(param_roughness_scale, '', roughness_range, 'B')
        nb_link(roughness_range_t_clamp, '', roughness_range, 'Alpha')
        nb_output(roughness_range, '', unreal.MaterialProperty.MP_ROUGHNESS)
        constant_2 = nb_expression(material, "MaterialExpressionConstant", -400, 3360)
        nb_prop(constant_2, "r", 0.5)
        nb_output(constant_2, '', unreal.MaterialProperty.MP_SPECULAR)
        # Rock Bump: BUMP [APPROXIMATE]
        rock_bump_ddx = nb_expression(material, "MaterialExpressionDDX", -660, 3500)
        nb_link(rock_noise, '', rock_bump_ddx, '')
        rock_bump_ddy = nb_expression(material, "MaterialExpressionDDY", -920, 3640)
        nb_link(rock_noise, '', rock_bump_ddy, '')
        rock_bump_gx = nb_expression(material, "MaterialExpressionMultiply", -1180, 3780)
        nb_link(rock_bump_ddx, '', rock_bump_gx, 'A')
        nb_prop(rock_bump_gx, "const_b", -35.0)
        rock_bump_gy = nb_expression(material, "MaterialExpressionMultiply", -1440, 3920)
        nb_link(rock_bump_ddy, '', rock_bump_gy, 'A')
        nb_prop(rock_bump_gy, "const_b", -35.0)
        rock_bump_xy = nb_expression(material, "MaterialExpressionAppendVector", -1700, 4060)
        nb_link(rock_bump_gx, '', rock_bump_xy, 'A')
        nb_link(rock_bump_gy, '', rock_bump_xy, 'B')
        rock_bump_xyz = nb_expression(material, "MaterialExpressionAppendVector", -400, 4200)
        nb_link(rock_bump_xy, '', rock_bump_xyz, 'A')
        constant_3 = nb_expression(material, "MaterialExpressionConstant", -660, 4340)
        nb_prop(constant_3, "r", 1.0)
        nb_link(constant_3, '', rock_bump_xyz, 'B')
        rock_bump_normal = nb_expression(material, "MaterialExpressionNormalize", -920, 4480)
        nb_link(rock_bump_xyz, '', rock_bump_normal, '')
        nb_output(rock_bump_normal, '', unreal.MaterialProperty.MP_NORMAL)
        MEL.recompile_material(material)
        unreal.EditorAssetLibrary.save_loaded_asset(material)
        return material
    created['ProceduralRock'] = build_material_procedural_rock()
    return created

def build():
    materials = build_materials()
    factory_class = getattr(unreal, "PCGGraphFactory", None)
    graph = nb_create_asset("PCG_ScatterRocks", ASSET_PATH, unreal.PCGGraph, factory_class() if factory_class else None)
    input_node = graph.get_input_node()
    output_node = graph.get_output_node()

    # Geometry: GEOMETRY_INPUT [EQUIVALENT] -> PCG graph Input node  (Blender: NodeGroupInput)

    # Rock Shape: PRIMITIVE [APPROXIMATE] -> Engine basic shape  (Blender: GeometryNodeMeshIcoSphere)

    # Scatter Rocks: SCATTER [EQUIVALENT] -> PCGSurfaceSamplerSettings  (Blender: GeometryNodeDistributePointsOnFaces)
    scatter_rocks, scatter_rocks_settings = nb_pcg_node(graph, "PCGSurfaceSamplerSettings", 800, 0)
    nb_edge(graph, input_node, ['Input', 'In'], scatter_rocks, ['Surface', 'In'])
    nb_prop(scatter_rocks_settings, "points_per_squared_meter", DENSITY)
    nb_prop(scatter_rocks_settings, "seed", int(SEED))

    # Sink Rock: TRANSFORM [APPROXIMATE] -> Transform Points scale  (Blender: GeometryNodeTransform)

    # Remove Sparse Areas: DELETE_GEOMETRY [APPROXIMATE] -> PCGSpatialNoiseSettings + PCGDensityFilterSettings  (Blender: GeometryNodeDeleteGeometry)
    remove_sparse_areas_noise, remove_sparse_areas_noise_settings = nb_pcg_node(graph, "PCGSpatialNoiseSettings", 1200, 0)
    nb_edge(graph, scatter_rocks, ['Out'], remove_sparse_areas_noise, ['In'])
    nb_prop(remove_sparse_areas_noise_settings, "mode", nb_enum("PCGSpatialNoiseMode", "FRACTIONAL_BROWNIAN2D", "FRACTIONAL_BROWNIAN", "PERLIN2D"))
    nb_prop(remove_sparse_areas_noise_settings, "iterations", 4)
    # Blender noise scale 0.35 per meter; PCG Spatial Noise scales in world units.
    remove_sparse_areas_geometry_filter, remove_sparse_areas_geometry_filter_settings = nb_pcg_node(graph, "PCGDensityFilterSettings", 1200, 250)
    nb_edge(graph, remove_sparse_areas_noise, ['Out'], remove_sparse_areas_geometry_filter, ['In'])
    nb_prop(remove_sparse_areas_geometry_filter_settings, "lower_bound", 0.3 + (COVERAGE - 0.0) / 1.0 * 0.4)
    nb_prop(remove_sparse_areas_geometry_filter_settings, "upper_bound", 1.0)

    # Rock Material: MATERIAL_ASSIGNMENT [EQUIVALENT] -> Static Mesh Spawner override material  (Blender: GeometryNodeSetMaterial)

    # Random Scale: RANDOM_TRANSFORM [EQUIVALENT] -> PCGTransformPointsSettings  (Blender: FunctionNodeRandomValue, GeometryNodeInstanceOnPoints)
    random_scale, random_scale_settings = nb_pcg_node(graph, "PCGTransformPointsSettings", 1600, 0)
    nb_edge(graph, remove_sparse_areas_geometry_filter, ['Out'], random_scale, ['In'])
    nb_prop(random_scale_settings, "uniform_scale", True)
    nb_prop(random_scale_settings, "scale_min", unreal.Vector(SCALE_MIN, SCALE_MIN, SCALE_MIN))
    nb_prop(random_scale_settings, "scale_max", unreal.Vector(SCALE_MAX, SCALE_MAX, SCALE_MAX))
    nb_prop(random_scale_settings, "seed", int(SEED))

    # Random Rotation: RANDOM_TRANSFORM [EQUIVALENT] -> PCGTransformPointsSettings  (Blender: FunctionNodeRandomValue, GeometryNodeRotateInstances)
    random_rotation, random_rotation_settings = nb_pcg_node(graph, "PCGTransformPointsSettings", 2000, 0)
    nb_edge(graph, random_scale, ['Out'], random_rotation, ['In'])
    nb_prop(random_rotation_settings, "rotation_min", unreal.Rotator(roll=0.0, pitch=0.0, yaw=-360.0))
    nb_prop(random_rotation_settings, "rotation_max", unreal.Rotator(roll=0.0, pitch=0.0, yaw=0.0))
    nb_prop(random_rotation_settings, "seed", int(3))

    # Place Rocks: INSTANCE [APPROXIMATE] -> PCGStaticMeshSpawnerSettings  (Blender: GeometryNodeInstanceOnPoints, GeometryNodeRotateInstances)
    place_rocks_mesh_size, place_rocks_mesh_size_settings = nb_pcg_node(graph, "PCGTransformPointsSettings", 2400, 0)
    nb_edge(graph, random_rotation, ['Out'], place_rocks_mesh_size, ['In'])
    nb_prop(place_rocks_mesh_size_settings, "scale_min", unreal.Vector(0.5, 0.5, 0.3))
    nb_prop(place_rocks_mesh_size_settings, "scale_max", unreal.Vector(0.5, 0.5, 0.3))
    place_rocks, place_rocks_settings = nb_pcg_node(graph, "PCGStaticMeshSpawnerSettings", 2400, 250)
    nb_edge(graph, place_rocks_mesh_size, ['Out'], place_rocks, ['In'])
    nb_spawner_mesh(place_rocks_settings, "/Engine/BasicShapes/Sphere.Sphere", materials.get('ProceduralRock'))

    # Realize Instances: REALIZE_INSTANCES [APPROXIMATE] -> none (pass-through)  (Blender: GeometryNodeRealizeInstances)

    # Join Geometry: MERGE [EQUIVALENT] -> PCGMergeSettings  (Blender: GeometryNodeJoinGeometry)
    join_geometry, join_geometry_settings = nb_pcg_node(graph, "PCGMergeSettings", 3200, 0)
    nb_edge(graph, place_rocks, ['Out'], join_geometry, ['In'])

    # Geometry: GEOMETRY_OUTPUT [EQUIVALENT] -> PCG graph Output node  (Blender: NodeGroupOutput)
    nb_edge(graph, join_geometry, ['Out'], output_node, ['Out', 'Output'])

    unreal.EditorAssetLibrary.save_loaded_asset(graph)
    if SPAWN_PCG_VOLUME:
        actors = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
        volume = actors.spawn_actor_from_class(unreal.PCGVolume, unreal.Vector(0.0, 0.0, 0.0))
        component = volume.get_component_by_class(unreal.PCGComponent)
        component.set_graph(graph)
    return graph

graph = build()
print("NodeBridge: created", graph.get_path_name())
for nb_warning in NB_WARNINGS:
    unreal.log_warning("NodeBridge: " + nb_warning)
