"""NodeBridge: generated Houdini Python.

Source:  Geometry Nodes / ScatterRocks (Blender 4.2.23 LTS)
Target:  Houdini (SOP network)
Translation: 10 exact, 9 equivalent, 2 approximate, 0 unsupported
Generated by NodeBridge 0.3.0.

Run inside Houdini: Windows > Python Source Editor, paste this script, click Apply.
The script only creates new nodes; existing scene content is not modified.
Equivalent / approximate operations are marked with sticky notes in the network.
"""
import hou

NB_WARNINGS = []
NB_NOTES = []


def nb_unique_name(parent, name):
    """Never overwrite existing nodes: append a number if the name is taken."""
    candidate, index = name, 1
    while parent.node(candidate) is not None:
        index += 1
        candidate = "%s%d" % (name, index)
    return candidate


def nb_create(parent, node_type, name, **kwargs):
    return parent.createNode(node_type, nb_unique_name(parent, name), **kwargs)


def nb_set(node, parm_name, value):
    """Set a parameter (or parameter tuple) if this Houdini version has it."""
    if isinstance(value, (tuple, list)):
        parm_tuple = node.parmTuple(parm_name)
        if parm_tuple is not None:
            parm_tuple.set(value)
            return True
    parm = node.parm(parm_name)
    if parm is not None:
        parm.set(value)
        return True
    NB_WARNINGS.append("%s: parameter '%s' not found" % (node.path(), parm_name))
    return False


def nb_set_menu(node, parm_name, token):
    """Set a menu parameter by token, whether the menu stores strings or indices."""
    parm = node.parm(parm_name)
    if parm is None:
        NB_WARNINGS.append("%s: parameter '%s' not found" % (node.path(), parm_name))
        return False
    tokens = parm.menuItems()
    if token not in tokens:
        NB_WARNINGS.append("%s: '%s' is not an option of '%s' (%s)" % (node.path(), token, parm_name, ", ".join(tokens)))
        return False
    if parm.parmTemplate().dataType() == hou.parmData.String:
        parm.set(token)
    else:
        parm.set(tokens.index(token))
    return True


def nb_expr(node, parm_name, expression, index=None):
    """Drive a parameter with an HScript expression (e.g. a channel reference)."""
    if index is None:
        parm = node.parm(parm_name)
    else:
        parm_tuple = node.parmTuple(parm_name)
        parm = parm_tuple[index] if parm_tuple is not None else None
    if parm is None:
        NB_WARNINGS.append("%s: parameter '%s' not found for expression" % (node.path(), parm_name))
        return False
    parm.setExpression(expression, hou.exprLanguage.Hscript)
    return True


def nb_add_parameters(node, folder_label, templates):
    """Expose controls as spare parameters on a container node."""
    if not templates:
        return
    group = node.parmTemplateGroup()
    folder = hou.FolderParmTemplate("nodebridge_controls", folder_label, folder_type=hou.folderType.Tabs)
    for template in templates:
        folder.addParmTemplate(template)
    group.append(folder)
    node.setParmTemplateGroup(group)


def nb_note(parent, text, near=None):
    note = parent.createStickyNote()
    note.setText(text)
    NB_NOTES.append((note, near))
    return note


def nb_place_notes():
    for note, near in NB_NOTES:
        if near is not None:
            note.setPosition(near.position() + hou.Vector2(2.0, -0.5))
        note.setSize(hou.Vector2(5.0, 1.6))


def nb_connect(node, input_name, source, output=0):
    """Connect by input name (VOP networks); report instead of failing."""
    try:
        node.setNamedInput(input_name, source, output)
        return True
    except hou.Error as exc:
        NB_WARNINGS.append("%s: could not connect '%s' (%s)" % (node.path(), input_name, exc))
        return False


def nb_meta(node, comment, data):
    node.setComment(comment)
    node.setGenericFlag(hou.nodeFlag.DisplayComment, True)
    node.setUserData("nodebridge", data)

NB_VEX_HEADER = "#include <math.h>\n\n"
NB_VEX_COORDINATES = """\
// NodeBridge coordinate conversion (Blender Z-up <-> Houdini Y-up).
vector nb_b(vector h) { return set(h.x, -h.z, h.y); }
vector nb_h(vector b) { return set(b.x, b.z, -b.y); }
vector nb_bs(vector h) { return set(h.x, h.z, h.y); }
vector nb_hs(vector b) { return set(b.x, b.z, b.y); }
vector4 nb_orient_h(vector euler_b) {
    vector4 qb = eulertoquaternion(euler_b, XFORM_XYZ);
    vector4 c = quaternion(radians(-90.0), {1, 0, 0});
    return qmultiply(qmultiply(c, qb), qinvert(c));
}
"""
NB_VEX_RANDOM = """\
// NodeBridge deterministic random: identical to nodebridge.common.random.
int nb_lcg(int x) {
    int hi = x / 44488;
    int lo = x % 44488;
    x = 48271 * lo - 3399 * hi;
    if (x <= 0) x += 2147483647;
    return x;
}

int nb_mix(int x) {
    x = nb_lcg(x);
    return (x ^ (x >> 13)) % 2147483646 + 1;
}

int nb_hash(int seed; int id; int stream) {
    int x = abs(id) % 2147483646 + 1;
    x = nb_mix(x);
    x = (x ^ (abs(seed) % 2147483646)) % 2147483646 + 1;
    x = nb_mix(x);
    x = (x ^ (abs(stream) % 2147483646)) % 2147483646 + 1;
    return nb_mix(nb_mix(x));
}

float nb_random(int seed; int id; int stream) {
    return (nb_hash(seed, id, stream) - 1) / 2147483645.0;
}
"""
NB_VEX_NOISE = """\
// Fractal noise in the spirit of Blender's fBm Noise Texture (not numerically identical).
float nb_fbm(vector p; float detail; float roughness; float lacunarity) {
    float fscale = 1.0;
    float amp = 1.0;
    float maxamp = 0.0;
    float sum = 0.0;
    int octaves = int(floor(clamp(detail, 0.0, 15.0)));
    for (int i = 0; i <= octaves; i++) {
        sum += (noise(p * fscale) * 2.0 - 1.0) * amp;
        maxamp += amp;
        amp *= clamp(roughness, 0.0, 1.0);
        fscale *= lacunarity;
    }
    float rmd = detail - floor(detail);
    if (rmd > 0.0) {
        sum += (noise(p * fscale) * 2.0 - 1.0) * amp * rmd;
        maxamp += amp * rmd;
    }
    return maxamp > 0.0 ? 0.5 * sum / maxamp + 0.5 : 0.5;
}
"""

def build_materials():
    """Materials referenced by Set Material nodes."""
    created = {}

    def build_material_procedural_rock():
        """Material 'ProceduralRock' as a MaterialX network in /mat."""
        matnet = hou.node("/mat")
        # Principled BSDF: SHADER_BSDF [EQUIVALENT]
        procedural_rock = nb_create(matnet, "mtlxstandard_surface", "procedural_rock")
        # Rock Colors: COLOR_RAMP [EXACT]
        rock_colors_stop_0 = nb_create(matnet, "mtlxconstant", "rock_colors_stop_0")
        nb_set_menu(rock_colors_stop_0, "signature", "color3")
        nb_set(rock_colors_stop_0, "value", (0.08, 0.07, 0.06))
        rock_colors_segment_1 = nb_create(matnet, "mtlxremap", "rock_colors_segment_1")
        # Rock Noise: NOISE [APPROXIMATE]
        rock_noise_scale = nb_create(matnet, "mtlxmultiply", "rock_noise_scale")
        nb_set_menu(rock_noise_scale, "signature", "vector3")
        nb_set_menu(rock_noise_scale, "signature", "vector3FA")
        # Mapping: MAPPING [EXACT]
        mapping_scale = nb_create(matnet, "mtlxmultiply", "mapping_scale")
        nb_set_menu(mapping_scale, "signature", "vector3")
        # Texture Coordinate Object: FIELD_INPUT [EQUIVALENT]
        texture_coordinate_object = nb_create(matnet, "mtlxposition", "texture_coordinate_object")
        nb_set_menu(texture_coordinate_object, "signature", "vector3")
        nb_set_menu(texture_coordinate_object, "space", "object")
        nb_connect(mapping_scale, "in1", texture_coordinate_object, 0)
        nb_set(mapping_scale, "in2", (2.0, 2.0, 2.0))
        mapping_offset = nb_create(matnet, "mtlxadd", "mapping_offset")
        nb_set_menu(mapping_offset, "signature", "vector3")
        nb_connect(mapping_offset, "in1", mapping_scale, 0)
        nb_set(mapping_offset, "in2", (0.0, 0.0, 0.0))
        nb_connect(rock_noise_scale, "in1", mapping_offset, 0)
        nb_set(rock_noise_scale, "in2", 4.0)
        rock_noise = nb_create(matnet, "mtlxfractal3d", "rock_noise")
        nb_connect(rock_noise, "position", rock_noise_scale, 0)
        nb_set(rock_noise, "octaves", 9)
        nb_set(rock_noise, "diminish", 0.6)
        nb_set(rock_noise, "lacunarity", 2.0)
        rock_noise_to_unit = nb_create(matnet, "mtlxremap", "rock_noise_to_unit")
        nb_connect(rock_noise_to_unit, "in", rock_noise, 0)
        nb_set(rock_noise_to_unit, "inlow", -1.0)
        nb_set(rock_noise_to_unit, "inhigh", 1.0)
        nb_connect(rock_colors_segment_1, "in", rock_noise_to_unit, 0)
        nb_set(rock_colors_segment_1, "inlow", 0.3)
        nb_set(rock_colors_segment_1, "inhigh", 0.5)
        rock_colors_segment_1_clamp = nb_create(matnet, "mtlxclamp", "rock_colors_segment_1_clamp")
        nb_connect(rock_colors_segment_1_clamp, "in", rock_colors_segment_1, 0)
        rock_colors_stop_1 = nb_create(matnet, "mtlxmix", "rock_colors_stop_1")
        nb_set_menu(rock_colors_stop_1, "signature", "color3")
        nb_connect(rock_colors_stop_1, "bg", rock_colors_stop_0, 0)
        nb_set(rock_colors_stop_1, "fg", (0.25, 0.2, 0.15))
        nb_connect(rock_colors_stop_1, "mix", rock_colors_segment_1_clamp, 0)
        rock_colors_segment_2 = nb_create(matnet, "mtlxremap", "rock_colors_segment_2")
        nb_connect(rock_colors_segment_2, "in", rock_noise_to_unit, 0)
        nb_set(rock_colors_segment_2, "inlow", 0.5)
        nb_set(rock_colors_segment_2, "inhigh", 0.75)
        rock_colors_segment_2_clamp = nb_create(matnet, "mtlxclamp", "rock_colors_segment_2_clamp")
        nb_connect(rock_colors_segment_2_clamp, "in", rock_colors_segment_2, 0)
        rock_colors_stop_2 = nb_create(matnet, "mtlxmix", "rock_colors_stop_2")
        nb_set_menu(rock_colors_stop_2, "signature", "color3")
        nb_connect(rock_colors_stop_2, "bg", rock_colors_stop_1, 0)
        nb_set(rock_colors_stop_2, "fg", (0.55, 0.5, 0.42))
        nb_connect(rock_colors_stop_2, "mix", rock_colors_segment_2_clamp, 0)
        nb_connect(procedural_rock, "base_color", rock_colors_stop_2, 0)
        nb_set(procedural_rock, "metalness", 0.0)
        # Roughness Range: MAP_RANGE [EXACT]
        roughness_range = nb_create(matnet, "mtlxremap", "roughness_range")
        nb_connect(roughness_range, "in", rock_noise_to_unit, 0)
        nb_set(roughness_range, "inlow", 0.0)
        nb_set(roughness_range, "inhigh", 1.0)
        nb_set(roughness_range, "outlow", 0.45)
        roughness_scale = nb_create(matnet, "mtlxconstant", "roughness_scale")
        nb_set(roughness_scale, "value", 0.9)
        nb_connect(roughness_range, "outhigh", roughness_scale, 0)
        roughness_range_clamp = nb_create(matnet, "mtlxclamp", "roughness_range_clamp")
        nb_connect(roughness_range_clamp, "in", roughness_range, 0)
        nb_set(roughness_range_clamp, "low", 0.45)
        nb_connect(roughness_range_clamp, "high", roughness_scale, 0)
        nb_connect(procedural_rock, "specular_roughness", roughness_range_clamp, 0)
        nb_set(procedural_rock, "specular_IOR", 1.5)
        # Rock Bump: BUMP [EQUIVALENT]
        rock_bump = nb_create(matnet, "mtlxheighttonormal", "rock_bump")
        nb_connect(rock_bump, "in", rock_noise_to_unit, 0)
        nb_set(rock_bump, "scale", 0.35)
        nb_connect(procedural_rock, "normal", rock_bump, 0)
        nb_set(procedural_rock, "emission_color", (1.0, 1.0, 1.0))
        nb_set(procedural_rock, "emission", 0.0)
        nb_set(procedural_rock, "transmission", 0.0)
        nb_set(procedural_rock, "coat", 0.0)
        nb_set(procedural_rock, "coat_roughness", 0.03)
        nb_set(procedural_rock, "sheen", 0.0)
        nb_set(procedural_rock, "subsurface", 0.0)
        nb_set(procedural_rock, "specular", 1.0)
        nb_set(procedural_rock, "opacity", (1.0, 1.0, 1.0))
        material_nodes = (
            procedural_rock,
            rock_colors_stop_0,
            rock_colors_segment_1,
            rock_noise_scale,
            mapping_scale,
            texture_coordinate_object,
            mapping_offset,
            rock_noise,
            rock_noise_to_unit,
            rock_colors_segment_1_clamp,
            rock_colors_stop_1,
            rock_colors_segment_2,
            rock_colors_segment_2_clamp,
            rock_colors_stop_2,
            roughness_range,
            roughness_scale,
            roughness_range_clamp,
            rock_bump,
        )
        matnet.layoutChildren(items=material_nodes)
        nb_box = matnet.createNetworkBox()
        for nb_item in material_nodes:
            nb_box.addItem(nb_item)
        nb_box.setComment('ProceduralRock')
        nb_box.fitAroundContents()
        return procedural_rock
    created['ProceduralRock'] = build_material_procedural_rock().path()
    return created

def build():
    obj = hou.node("/obj")
    geo = nb_create(obj, "geo", "nb_scatter_rocks", run_init_scripts=False)
    nb_add_parameters(geo, 'ScatterRocks', [
        hou.FloatParmTemplate('density', 'Density', 1, default_value=(4.0,), min=0.0, max=100.0),
        hou.IntParmTemplate('seed', 'Seed', 1, default_value=(7,)),
        hou.FloatParmTemplate('scale_min', 'Scale Min', 1, default_value=(0.6,), min=0.0, max=10.0),
        hou.FloatParmTemplate('scale_max', 'Scale Max', 1, default_value=(1.4,), min=0.0, max=10.0),
        hou.FloatParmTemplate('coverage', 'Coverage', 1, default_value=(0.45,), min=0.0, max=1.0),
        hou.ToggleParmTemplate("use_source_object", "Use Source Object", default_value=False),
    ])
    materials = build_materials()

    # Geometry: GEOMETRY_INPUT [EQUIVALENT] -> object_merge + placeholder grid + switch  (Blender: NodeGroupInput)
    in_geometry_object = nb_create(geo, "object_merge", "IN_Geometry_object")
    nb_meta(in_geometry_object, 'NodeBridge: Geometry (EQUIVALENT)', '{"op": "GEOMETRY_INPUT", "source": ["NodeGroupInput"], "confidence": "EQUIVALENT"}')
    nb_set(in_geometry_object, "objpath1", '')
    nb_set(in_geometry_object, "xformtype", 1)
    in_geometry_placeholder = nb_create(geo, "grid", "IN_Geometry_placeholder")
    nb_set(in_geometry_placeholder, "size", (20.0, 20.0))
    nb_set_menu(in_geometry_placeholder, "orient", "xy")
    nb_set(in_geometry_placeholder, "r", (-90.0, 0.0, 0.0))
    nb_set(in_geometry_placeholder, "rows", 2)
    nb_set(in_geometry_placeholder, "cols", 2)
    in_geometry = nb_create(geo, "switch", "IN_Geometry")
    in_geometry.setInput(0, in_geometry_placeholder)
    in_geometry.setInput(1, in_geometry_object)
    nb_expr(in_geometry, "input", 'ch("../use_source_object")')
    nb_note(geo, "Point 'Object 1' at the object that carried the Blender modifier, then enable 'Use Source Object' on the geo node.", in_geometry_object)

    # Rock Shape: PRIMITIVE [EQUIVALENT] -> sphere SOP (polygon)  (Blender: GeometryNodeMeshIcoSphere)
    rock_shape = nb_create(geo, "sphere", "rock_shape")
    nb_meta(rock_shape, 'NodeBridge: Rock Shape (EQUIVALENT)', '{"op": "PRIMITIVE", "source": ["GeometryNodeMeshIcoSphere"], "confidence": "EQUIVALENT"}')
    nb_set_menu(rock_shape, "type", "poly")
    nb_set(rock_shape, "radx", 0.25)
    nb_set(rock_shape, "rady", 0.25)
    nb_set(rock_shape, "radz", 0.25)
    nb_set(rock_shape, "freq", 2)

    # Scatter Rocks: SCATTER [EQUIVALENT] -> scatter SOP  (Blender: GeometryNodeDistributePointsOnFaces)
    scatter_rocks = nb_create(geo, "scatter", "scatter_rocks")
    nb_meta(scatter_rocks, 'NodeBridge: Scatter Rocks (EQUIVALENT)', '{"op": "SCATTER", "source": ["GeometryNodeDistributePointsOnFaces"], "confidence": "EQUIVALENT"}')
    scatter_rocks.setInput(0, in_geometry)
    nb_set(scatter_rocks, "forcetotal", 0)
    nb_expr(scatter_rocks, "densityscale", 'ch("../density")')
    nb_expr(scatter_rocks, "seed", 'int(ch("../seed"))')
    nb_set(scatter_rocks, "relaxpoints", 0)

    # Sink Rock: TRANSFORM [EXACT] -> xform SOP  (Blender: GeometryNodeTransform)
    sink_rock = nb_create(geo, "xform", "sink_rock")
    nb_meta(sink_rock, 'NodeBridge: Sink Rock (EXACT)', '{"op": "TRANSFORM", "source": ["GeometryNodeTransform"], "confidence": "EXACT"}')
    sink_rock.setInput(0, rock_shape)
    nb_set_menu(sink_rock, "rOrd", "xzy")
    nb_set(sink_rock, "t", (0.0, -0.05, 0.0))
    nb_set(sink_rock, "r", (0.0, 0.0, 0.0))
    nb_set(sink_rock, "s", (1.0, 0.6, 1.0))

    # Remove Sparse Areas: DELETE_GEOMETRY [EXACT] -> attribwrangle removepoint()/removeprim()  (Blender: GeometryNodeDeleteGeometry)
    remove_sparse_areas = nb_create(geo, "attribwrangle", "remove_sparse_areas")
    nb_meta(remove_sparse_areas, 'NodeBridge: Remove Sparse Areas (EXACT)', '{"op": "DELETE_GEOMETRY", "source": ["GeometryNodeDeleteGeometry"], "confidence": "EXACT"}')
    remove_sparse_areas.setInput(0, scatter_rocks)
    nb_set(remove_sparse_areas, "class", 2)
    remove_sparse_areas_vex = NB_VEX_HEADER + NB_VEX_COORDINATES + NB_VEX_NOISE + """\
// Blender fields: Position (implicit), Coverage Noise
vector nb_p1 = nb_b(v@P) * 0.35;
float nb_noise2 = nb_fbm(nb_p1, 3.0, 0.5, 2.0);
nb_noise2 = fit(nb_noise2, 0.3, 0.7, 0.0, 1.0);
if ((nb_noise2 < chf("../coverage"))) removepoint(0, @ptnum, 1);
"""
    nb_set(remove_sparse_areas, "snippet", remove_sparse_areas_vex)

    # Rock Material: MATERIAL_ASSIGNMENT [EQUIVALENT] -> material SOP  (Blender: GeometryNodeSetMaterial)
    rock_material = nb_create(geo, "material", "rock_material")
    nb_meta(rock_material, 'NodeBridge: Rock Material (EQUIVALENT)', '{"op": "MATERIAL_ASSIGNMENT", "source": ["GeometryNodeSetMaterial"], "confidence": "EQUIVALENT"}')
    rock_material.setInput(0, sink_rock)
    nb_set(rock_material, "shop_materialpath1", materials.get('ProceduralRock', '/mat/procedural_rock'))

    # Random Scale: RANDOM_TRANSFORM [EQUIVALENT] -> attribwrangle writing orient / scale  (Blender: FunctionNodeRandomValue, GeometryNodeInstanceOnPoints)
    random_scale = nb_create(geo, "attribwrangle", "random_scale")
    nb_meta(random_scale, 'NodeBridge: Random Scale (EQUIVALENT)', '{"op": "RANDOM_TRANSFORM", "source": ["FunctionNodeRandomValue", "GeometryNodeInstanceOnPoints"], "confidence": "EQUIVALENT"}')
    random_scale.setInput(0, remove_sparse_areas)
    nb_set(random_scale, "class", 2)
    random_scale_vex = NB_VEX_HEADER + NB_VEX_COORDINATES + NB_VEX_RANDOM + """\
int nb_id = haspointattrib(0, "id") ? point(0, "id", @ptnum) : @ptnum;
float nb_s = fit01(nb_random(chi("../seed"), nb_id, 0), chf("../scale_min"), chf("../scale_max"));
vector nb_scale = set(nb_s, nb_s, nb_s);
vector nb_prev = haspointattrib(0, "scale") ? point(0, "scale", @ptnum) : {1, 1, 1};
v@scale = nb_prev * nb_scale;
"""
    nb_set(random_scale, "snippet", random_scale_vex)

    # Random Rotation: RANDOM_TRANSFORM [EQUIVALENT] -> attribwrangle writing orient / scale  (Blender: FunctionNodeRandomValue, GeometryNodeRotateInstances)
    random_rotation = nb_create(geo, "attribwrangle", "random_rotation")
    nb_meta(random_rotation, 'NodeBridge: Random Rotation (EQUIVALENT)', '{"op": "RANDOM_TRANSFORM", "source": ["FunctionNodeRandomValue", "GeometryNodeRotateInstances"], "confidence": "EQUIVALENT"}')
    random_rotation.setInput(0, random_scale)
    nb_set(random_rotation, "class", 2)
    random_rotation_vex = NB_VEX_HEADER + NB_VEX_COORDINATES + NB_VEX_RANDOM + """\
int nb_id = haspointattrib(0, "id") ? point(0, "id", @ptnum) : @ptnum;
vector nb_rlo = set(0.0, 0.0, 0.0);
vector nb_rhi = set(0.0, 0.0, 6.283185);
vector nb_euler = set(fit01(nb_random(3, nb_id, 0), nb_rlo.x, nb_rhi.x), fit01(nb_random(3, nb_id, 1), nb_rlo.y, nb_rhi.y), fit01(nb_random(3, nb_id, 2), nb_rlo.z, nb_rhi.z));
vector4 nb_q = haspointattrib(0, "orient") ? point(0, "orient", @ptnum) : {0, 0, 0, 1};
p@orient = qmultiply(nb_q, nb_orient_h(nb_euler));
"""
    nb_set(random_rotation, "snippet", random_rotation_vex)

    # Place Rocks: INSTANCE [EXACT] -> copytopoints SOP (Pack and Instance)  (Blender: GeometryNodeInstanceOnPoints, GeometryNodeRotateInstances)
    place_rocks = nb_create(geo, "copytopoints", "place_rocks")
    nb_meta(place_rocks, 'NodeBridge: Place Rocks (EXACT)', '{"op": "INSTANCE", "source": ["GeometryNodeInstanceOnPoints", "GeometryNodeRotateInstances"], "confidence": "EXACT"}')
    place_rocks.setInput(0, rock_material)
    place_rocks.setInput(1, random_rotation)
    nb_set(place_rocks, "pack", 1)
    nb_set(place_rocks, "useimplicitn", 0)

    # Realize Instances: REALIZE_INSTANCES [EXACT] -> unpack SOP  (Blender: GeometryNodeRealizeInstances)
    realize_instances = nb_create(geo, "unpack", "realize_instances")
    nb_meta(realize_instances, 'NodeBridge: Realize Instances (EXACT)', '{"op": "REALIZE_INSTANCES", "source": ["GeometryNodeRealizeInstances"], "confidence": "EXACT"}')
    realize_instances.setInput(0, place_rocks)

    # Join Geometry: MERGE [EXACT] -> merge SOP  (Blender: GeometryNodeJoinGeometry)
    join_geometry = nb_create(geo, "merge", "join_geometry")
    nb_meta(join_geometry, 'NodeBridge: Join Geometry (EXACT)', '{"op": "MERGE", "source": ["GeometryNodeJoinGeometry"], "confidence": "EXACT"}')
    join_geometry.setInput(0, realize_instances)
    join_geometry.setInput(1, in_geometry)

    # Geometry: GEOMETRY_OUTPUT [EXACT] -> null OUT (display/render)  (Blender: NodeGroupOutput)
    out = nb_create(geo, "null", "OUT")
    out.setInput(0, join_geometry)
    out.setDisplayFlag(True)
    out.setRenderFlag(True)

    geo.layoutChildren()
    nb_place_notes()
    return geo

geo = build()
print("NodeBridge: created", geo.path())
for nb_warning in NB_WARNINGS:
    print("NodeBridge warning:", nb_warning)
