# Generated by NodeBridge 0.3.0
# Houdini SOP network
# Source: geometry / BuildingGenerator
#
# Paste this script into the Houdini Python Source Editor and run it.
# It builds an editable native network. It does not import baked geometry.
# Loading a .nodebridge.json file does not execute this script.
# Coordinates: Blender Z-up right-handed -> Houdini Y-up right-handed.
#     position' = (x, z, -y)
# Units: lengths stay in meters when the source is Blender.
#     Rotations are converted from radians to degrees for Transform SOPs.
# Randomness: Scatter and Attribute Randomize do not reproduce Blender's sequence.
#     NodeBridge's hash random is emitted only into wrangles that implement random values
#     when deterministic randomness is enabled. It is not Blender's random.

import hou

def _create(parent, node_type, name):
    category = parent.childTypeCategory()
    if hou.nodeType(category, node_type) is None:
        raise hou.NodeError(
            'NodeBridge expected Houdini node type %r in %s. '
            'This build does not provide it, so the operation was not skipped silently.'
            % (node_type, parent.path())
        )
    return parent.createNode(node_type, name)

def _set(node, name, value):
    parm = node.parmTuple(name) if isinstance(value, (list, tuple)) else node.parm(name)
    if parm is None:
        parm = node.parm(name)
    if parm is None:
        return False
    parm.set(value)
    return True

def build(parent=None):
    parent = parent or hou.node('/obj')
    name = 'buildinggenerator'
    # Always create a new Geometry container. Existing scene nodes are not modified.
    geo = parent.createNode('geo', name)
    for child in list(geo.children()):
        child.destroy()
    created = {}

    # Reference implementation of NodeBridge random(seed, element_id).
    # Paste into a wrangle only where a comment below says to use it.
    # // NodeBridge deterministic random. Not Blender's or Houdini's rand().
    # int nb_mix(int value) {
    #     value = value & 0xFFFFFFFF;
    #     value = value ^ (value >> 16);
    #     value = (value * 0x7FEB352D) & 0xFFFFFFFF;
    #     value = value ^ (value >> 15);
    #     value = (value * 0x846CA68B) & 0xFFFFFFFF;
    #     value = value ^ (value >> 16);
    #     return value;
    # }
    # float nb_random(int seed; int element_id) {
    #     int mixed = nb_mix((seed * 0x9E3779B1) ^ (element_id * 0x85EBCA6B));
    #     return float(mixed & 0xFFFFFF) / 16777216.0;
    # }

    cube = _create(geo, 'box', 'cube')
    _set(cube, 'size', [1.0, 1.0, 1.0])
    created['Cube__node'] = cube

    scatter_buildings = _create(geo, 'scatter', 'scatter_buildings')
    # EQUIVALENT: Scatter uses Houdini's random sequence. A constant density is converted to an approximate total point count.
    scatter_buildings.setComment("Scatter uses Houdini's random sequence. A constant density is converted to an approximate total point count.")
    _set(scatter_buildings, 'density', 12.5)
    _set(scatter_buildings, 'seed', 3)
    _set(scatter_buildings, 'npts', 125)
    created['Scatter_Buildings__node'] = scatter_buildings

    instance = _create(geo, 'copytopoints', 'instance')
    # EQUIVALENT: Copy to Points instances the template onto points; scale/rotation use point attributes when wired.
    instance.setComment('Copy to Points instances the template onto points; scale/rotation use point attributes when wired.')
    _set(instance, 's', [1.0, 1.0, 1.0])
    created['Instance__copy'] = instance

    realize = _create(geo, 'unpack', 'realize')
    # EQUIVALENT: Packed instances unpack then convert into explicit geometry.
    realize.setComment('Packed instances unpack then convert into explicit geometry.')
    created['Realize__unpack'] = realize

    realize_2 = _create(geo, 'convert', 'realize_2')
    # EQUIVALENT: Packed instances unpack then convert into explicit geometry.
    realize_2.setComment('Packed instances unpack then convert into explicit geometry.')
    created['Realize__convert'] = realize_2

    group_output = _create(geo, 'null', 'group_output')
    created['Group_Output__node'] = group_output

    realize_2.setInput(0, realize)
    scatter_buildings.setInput(0, cube)
    instance.setInput(1, scatter_buildings)
    instance.setInput(0, cube)
    realize.setInput(0, instance)
    group_output.setInput(0, realize_2)

    realize_2.setDisplayFlag(True)
    realize_2.setRenderFlag(True)
    _annotate(geo, created)
    for node in created.values():
        node.moveToGoodPosition()
    geo.layoutChildren()
    return geo

def _annotate(geo, created):
    notes = []
    for node in created.values():
        comment = node.comment()
        if comment:
            notes.append(node.name() + ': ' + comment)
    if not notes:
        return
    sticky = geo.createStickyNote()
    sticky.setText('NodeBridge\n' + '\n'.join(notes))
    sticky.setPosition(hou.Vector2(0, 2))

if __name__ == '__main__':
    build()
