"""NodeBridge: generated Unreal Editor Python.

Source:  Geometry Nodes / BuildingGenerator (Blender 4.2.23 LTS)
Target:  Unreal Engine 5 (PCG graph)
Translation: 4 exact, 3 equivalent, 5 approximate, 11 unsupported
Generated by NodeBridge 0.3.0.

Run inside the Unreal Editor with the Python Editor Script Plugin enabled:
save this file, then Tools > Execute Python Script (or paste into the Output Log's Python console).
Requires the PCG plugin. The PCG Python API is experimental (UE 5.4+); anything
this editor version does not expose is listed as a NodeBridge warning in the log.
New assets are created under ASSET_PATH; existing assets are never overwritten.
"""
import unreal

ASSET_PATH = "/Game/NodeBridge"
SPAWN_PCG_VOLUME = False  # True: also place a PCG Volume using the new graph

# Controls (Blender group inputs, Blender units). Edit and re-run to rebuild the graph.
WIDTH = 10.0  # Width
DEPTH = 8.0  # Depth
FLOORS = 6  # Floors
FLOOR_HEIGHT = 3.0  # Floor Height
WINDOW_DENSITY = 0.35  # Window Density
SEED = 1  # Seed
NB_WARNINGS = []


def nb_unique_asset_name(path, name):
    candidate, index = name, 1
    while unreal.EditorAssetLibrary.does_asset_exist("%s/%s" % (path, candidate)):
        index += 1
        candidate = "%s_%d" % (name, index)
    return candidate


def nb_create_asset(name, path, asset_class, factory):
    """Create a new asset; never overwrites an existing one."""
    unreal.EditorAssetLibrary.make_directory(path)
    name = nb_unique_asset_name(path, name)
    asset = unreal.AssetToolsHelpers.get_asset_tools().create_asset(name, path, asset_class, factory)
    if asset is None:
        raise RuntimeError("NodeBridge could not create %s/%s" % (path, name))
    return asset


def nb_class(name):
    cls = getattr(unreal, name, None)
    if cls is None:
        NB_WARNINGS.append("unreal.%s is not available in this Unreal version" % name)
    return cls


def nb_enum(enum_name, *candidates):
    enum = getattr(unreal, enum_name, None)
    for candidate in candidates:
        if enum is not None and hasattr(enum, candidate):
            return getattr(enum, candidate)
    NB_WARNINGS.append("unreal.%s has none of %s" % (enum_name, ", ".join(candidates)))
    return None


def nb_prop(obj, name, value):
    """set_editor_property with a warning instead of an exception."""
    if obj is None or value is None:
        return False
    try:
        obj.set_editor_property(name, value)
        return True
    except Exception as exc:
        NB_WARNINGS.append("%s.%s: %s" % (type(obj).__name__, name, exc))
        return False

def nb_pcg_node(graph, settings_class_name, x, y):
    settings_class = nb_class(settings_class_name)
    if settings_class is None:
        return None, None
    node, settings = graph.add_node_of_type(settings_class)
    try:
        node.set_node_position(x, y)
    except Exception:
        pass
    return node, settings


def nb_edge(graph, source, source_pins, target, target_pins):
    """Connect two PCG nodes, trying known pin labels across UE versions."""
    if source is None or target is None:
        return False
    for source_pin in source_pins:
        for target_pin in target_pins:
            if graph.add_edge(source, source_pin, target, target_pin) is not None:
                return True
    NB_WARNINGS.append("could not connect %s -> %s (pins %s / %s)" % (source_pins, target_pins, source_pins, target_pins))
    return False


def nb_spawner_mesh(settings, mesh_path, material=None):
    """Point a Static Mesh Spawner at one mesh (UE 5.2+ descriptor API, 5.0/5.1 fallback)."""
    mesh = unreal.EditorAssetLibrary.load_asset(mesh_path)
    if mesh is None:
        NB_WARNINGS.append("static mesh %s not found; assign one on the Static Mesh Spawner" % mesh_path)
        return False
    try:
        settings.set_mesh_selector_type(unreal.PCGMeshSelectorWeighted)
    except Exception:
        nb_prop(settings, "mesh_selector_type", getattr(unreal, "PCGMeshSelectorWeighted", None))
    selector = settings.get_editor_property("mesh_selector_parameters")
    entry = unreal.PCGMeshSelectorWeightedEntry()
    try:
        descriptor = entry.get_editor_property("descriptor")
        descriptor.set_editor_property("static_mesh", mesh)
        if material is not None:
            descriptor.set_editor_property("override_materials", [material])
        entry.set_editor_property("descriptor", descriptor)
    except Exception:
        nb_prop(entry, "mesh", mesh)
    nb_prop(entry, "weight", 1)
    return nb_prop(selector, "mesh_entries", [entry])

def build():
    factory_class = getattr(unreal, "PCGGraphFactory", None)
    graph = nb_create_asset("PCG_BuildingGenerator", ASSET_PATH, unreal.PCGGraph, factory_class() if factory_class else None)
    output_node = graph.get_output_node()

    # Window Panel: PRIMITIVE [APPROXIMATE] -> Engine basic shape  (Blender: GeometryNodeMeshCube)

    # Footprint: PRIMITIVE [UNSUPPORTED] -> none  (Blender: GeometryNodeMeshGrid)
    NB_WARNINGS.append('Not translated: Footprint (PRIMITIVE). PCG does not generate meshes; primitives are only translated as instance meshes.')

    # Building Mass: EXTRUDE [UNSUPPORTED] -> none  (Blender: GeometryNodeExtrudeMesh)
    NB_WARNINGS.append('Not translated: Building Mass (EXTRUDE). PCG works on point data; this modelling operation has no PCG node (a Geometry Script backend could cover it later).')

    # Floor Levels: PRIMITIVE [UNSUPPORTED] -> none  (Blender: GeometryNodeMeshLine)
    NB_WARNINGS.append('Not translated: Floor Levels (PRIMITIVE). PCG does not generate meshes; primitives are only translated as instance meshes.')

    # Slab Outline: PRIMITIVE [UNSUPPORTED] -> none  (Blender: GeometryNodeMeshGrid)
    NB_WARNINGS.append('Not translated: Slab Outline (PRIMITIVE). PCG does not generate meshes; primitives are only translated as instance meshes.')

    # Slab Thickness: EXTRUDE [UNSUPPORTED] -> none  (Blender: GeometryNodeExtrudeMesh)
    NB_WARNINGS.append('Not translated: Slab Thickness (EXTRUDE). PCG works on point data; this modelling operation has no PCG node (a Geometry Script backend could cover it later).')

    # Stack Floors: INSTANCE [UNSUPPORTED] -> none  (Blender: GeometryNodeInstanceOnPoints)
    NB_WARNINGS.append('Not translated: Stack Floors (INSTANCE). The instanced geometry is procedural; PCG spawns Static Mesh assets.')

    # Window Positions: SCATTER [APPROXIMATE] -> PCGSurfaceSamplerSettings  (Blender: GeometryNodeDistributePointsOnFaces)
    window_positions, window_positions_settings = nb_pcg_node(graph, "PCGSurfaceSamplerSettings", 2000, 0)
    nb_prop(window_positions_settings, "points_per_squared_meter", WINDOW_DENSITY)
    nb_prop(window_positions_settings, "seed", int(SEED))

    # Realize Floors: REALIZE_INSTANCES [APPROXIMATE] -> none (pass-through)  (Blender: GeometryNodeRealizeInstances)

    # Window Variation: RANDOM_TRANSFORM [EQUIVALENT] -> PCGTransformPointsSettings  (Blender: FunctionNodeRandomValue, GeometryNodeInstanceOnPoints)
    window_variation, window_variation_settings = nb_pcg_node(graph, "PCGTransformPointsSettings", 2400, 0)
    nb_edge(graph, window_positions, ['Out'], window_variation, ['In'])
    nb_prop(window_variation_settings, "uniform_scale", True)
    nb_prop(window_variation_settings, "scale_min", unreal.Vector(0.7, 0.7, 0.7))
    nb_prop(window_variation_settings, "scale_max", unreal.Vector(1.2, 1.2, 1.2))
    nb_prop(window_variation_settings, "seed", int(SEED))

    # Place Windows: INSTANCE [APPROXIMATE] -> PCGStaticMeshSpawnerSettings  (Blender: GeometryNodeInstanceOnPoints)
    place_windows_mesh_size, place_windows_mesh_size_settings = nb_pcg_node(graph, "PCGTransformPointsSettings", 2800, 0)
    nb_edge(graph, window_variation, ['Out'], place_windows_mesh_size, ['In'])
    nb_prop(place_windows_mesh_size_settings, "scale_min", unreal.Vector(0.9, 0.9, 1.3))
    nb_prop(place_windows_mesh_size_settings, "scale_max", unreal.Vector(0.9, 0.9, 1.3))
    place_windows, place_windows_settings = nb_pcg_node(graph, "PCGStaticMeshSpawnerSettings", 2800, 250)
    nb_edge(graph, place_windows_mesh_size, ['Out'], place_windows, ['In'])
    nb_spawner_mesh(place_windows_settings, "/Engine/BasicShapes/Cube.Cube", None)

    # Realize Windows: REALIZE_INSTANCES [APPROXIMATE] -> none (pass-through)  (Blender: GeometryNodeRealizeInstances)

    # Assemble Building: MERGE [EQUIVALENT] -> PCGMergeSettings  (Blender: GeometryNodeJoinGeometry)
    assemble_building, assemble_building_settings = nb_pcg_node(graph, "PCGMergeSettings", 3600, 0)
    nb_edge(graph, place_windows, ['Out'], assemble_building, ['In'])

    # Concrete: MATERIAL_ASSIGNMENT [UNSUPPORTED] -> none  (Blender: GeometryNodeSetMaterial)
    NB_WARNINGS.append('Not translated: Concrete (MATERIAL_ASSIGNMENT). Materials are only translated on spawned meshes.')

    # Geometry: GEOMETRY_OUTPUT [EQUIVALENT] -> PCG graph Output node  (Blender: NodeGroupOutput)
    nb_edge(graph, assemble_building, ['Out'], output_node, ['Out', 'Output'])

    unreal.EditorAssetLibrary.save_loaded_asset(graph)
    if SPAWN_PCG_VOLUME:
        actors = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
        volume = actors.spawn_actor_from_class(unreal.PCGVolume, unreal.Vector(0.0, 0.0, 0.0))
        component = volume.get_component_by_class(unreal.PCGComponent)
        component.set_graph(graph)
    return graph

graph = build()
print("NodeBridge: created", graph.get_path_name())
for nb_warning in NB_WARNINGS:
    unreal.log_warning("NodeBridge: " + nb_warning)
