"""NodeBridge: generated Houdini Python.

Source:  Geometry Nodes / BuildingGenerator (Blender 4.2.23 LTS)
Target:  Houdini (SOP network)
Translation: 21 exact, 3 equivalent, 0 approximate, 0 unsupported
Generated by NodeBridge 0.3.0.

Run inside Houdini: Windows > Python Source Editor, paste this script, click Apply.
The script only creates new nodes; existing scene content is not modified.
Equivalent / approximate operations are marked with sticky notes in the network.
"""
import hou

NB_WARNINGS = []
NB_NOTES = []


def nb_unique_name(parent, name):
    """Never overwrite existing nodes: append a number if the name is taken."""
    candidate, index = name, 1
    while parent.node(candidate) is not None:
        index += 1
        candidate = "%s%d" % (name, index)
    return candidate


def nb_create(parent, node_type, name, **kwargs):
    return parent.createNode(node_type, nb_unique_name(parent, name), **kwargs)


def nb_set(node, parm_name, value):
    """Set a parameter (or parameter tuple) if this Houdini version has it."""
    if isinstance(value, (tuple, list)):
        parm_tuple = node.parmTuple(parm_name)
        if parm_tuple is not None:
            parm_tuple.set(value)
            return True
    parm = node.parm(parm_name)
    if parm is not None:
        parm.set(value)
        return True
    NB_WARNINGS.append("%s: parameter '%s' not found" % (node.path(), parm_name))
    return False


def nb_set_menu(node, parm_name, token):
    """Set a menu parameter by token, whether the menu stores strings or indices."""
    parm = node.parm(parm_name)
    if parm is None:
        NB_WARNINGS.append("%s: parameter '%s' not found" % (node.path(), parm_name))
        return False
    tokens = parm.menuItems()
    if token not in tokens:
        NB_WARNINGS.append("%s: '%s' is not an option of '%s' (%s)" % (node.path(), token, parm_name, ", ".join(tokens)))
        return False
    if parm.parmTemplate().dataType() == hou.parmData.String:
        parm.set(token)
    else:
        parm.set(tokens.index(token))
    return True


def nb_expr(node, parm_name, expression, index=None):
    """Drive a parameter with an HScript expression (e.g. a channel reference)."""
    if index is None:
        parm = node.parm(parm_name)
    else:
        parm_tuple = node.parmTuple(parm_name)
        parm = parm_tuple[index] if parm_tuple is not None else None
    if parm is None:
        NB_WARNINGS.append("%s: parameter '%s' not found for expression" % (node.path(), parm_name))
        return False
    parm.setExpression(expression, hou.exprLanguage.Hscript)
    return True


def nb_add_parameters(node, folder_label, templates):
    """Expose controls as spare parameters on a container node."""
    if not templates:
        return
    group = node.parmTemplateGroup()
    folder = hou.FolderParmTemplate("nodebridge_controls", folder_label, folder_type=hou.folderType.Tabs)
    for template in templates:
        folder.addParmTemplate(template)
    group.append(folder)
    node.setParmTemplateGroup(group)


def nb_note(parent, text, near=None):
    note = parent.createStickyNote()
    note.setText(text)
    NB_NOTES.append((note, near))
    return note


def nb_place_notes():
    for note, near in NB_NOTES:
        if near is not None:
            note.setPosition(near.position() + hou.Vector2(2.0, -0.5))
        note.setSize(hou.Vector2(5.0, 1.6))


def nb_connect(node, input_name, source, output=0):
    """Connect by input name (VOP networks); report instead of failing."""
    try:
        node.setNamedInput(input_name, source, output)
        return True
    except hou.Error as exc:
        NB_WARNINGS.append("%s: could not connect '%s' (%s)" % (node.path(), input_name, exc))
        return False


def nb_meta(node, comment, data):
    node.setComment(comment)
    node.setGenericFlag(hou.nodeFlag.DisplayComment, True)
    node.setUserData("nodebridge", data)

NB_VEX_HEADER = "#include <math.h>\n\n"
NB_VEX_COORDINATES = """\
// NodeBridge coordinate conversion (Blender Z-up <-> Houdini Y-up).
vector nb_b(vector h) { return set(h.x, -h.z, h.y); }
vector nb_h(vector b) { return set(b.x, b.z, -b.y); }
vector nb_bs(vector h) { return set(h.x, h.z, h.y); }
vector nb_hs(vector b) { return set(b.x, b.z, b.y); }
vector4 nb_orient_h(vector euler_b) {
    vector4 qb = eulertoquaternion(euler_b, XFORM_XYZ);
    vector4 c = quaternion(radians(-90.0), {1, 0, 0});
    return qmultiply(qmultiply(c, qb), qinvert(c));
}
"""
NB_VEX_RANDOM = """\
// NodeBridge deterministic random: identical to nodebridge.common.random.
int nb_lcg(int x) {
    int hi = x / 44488;
    int lo = x % 44488;
    x = 48271 * lo - 3399 * hi;
    if (x <= 0) x += 2147483647;
    return x;
}

int nb_mix(int x) {
    x = nb_lcg(x);
    return (x ^ (x >> 13)) % 2147483646 + 1;
}

int nb_hash(int seed; int id; int stream) {
    int x = abs(id) % 2147483646 + 1;
    x = nb_mix(x);
    x = (x ^ (abs(seed) % 2147483646)) % 2147483646 + 1;
    x = nb_mix(x);
    x = (x ^ (abs(stream) % 2147483646)) % 2147483646 + 1;
    return nb_mix(nb_mix(x));
}

float nb_random(int seed; int id; int stream) {
    return (nb_hash(seed, id, stream) - 1) / 2147483645.0;
}
"""

def build():
    obj = hou.node("/obj")
    geo = nb_create(obj, "geo", "nb_building_generator", run_init_scripts=False)
    nb_add_parameters(geo, 'BuildingGenerator', [
        hou.FloatParmTemplate('width', 'Width', 1, default_value=(10.0,), min=1.0, max=100.0),
        hou.FloatParmTemplate('depth', 'Depth', 1, default_value=(8.0,), min=1.0, max=100.0),
        hou.IntParmTemplate('floors', 'Floors', 1, default_value=(6,), min=1, max=60),
        hou.FloatParmTemplate('floor_height', 'Floor Height', 1, default_value=(3.0,), min=2.0, max=10.0),
        hou.FloatParmTemplate('window_density', 'Window Density', 1, default_value=(0.35,), min=0.0, max=5.0),
        hou.IntParmTemplate('seed', 'Seed', 1, default_value=(1,)),
    ])

    # Window Panel: PRIMITIVE [EXACT] -> box SOP  (Blender: GeometryNodeMeshCube)
    window_panel = nb_create(geo, "box", "window_panel")
    nb_meta(window_panel, 'NodeBridge: Window Panel (EXACT)', '{"op": "PRIMITIVE", "source": ["GeometryNodeMeshCube"], "confidence": "EXACT"}')
    nb_set(window_panel, "size", (0.9, 1.3, 0.9))

    # Footprint: PRIMITIVE [EXACT] -> grid SOP  (Blender: GeometryNodeMeshGrid)
    footprint = nb_create(geo, "grid", "footprint")
    nb_meta(footprint, 'NodeBridge: Footprint (EXACT)', '{"op": "PRIMITIVE", "source": ["GeometryNodeMeshGrid"], "confidence": "EXACT"}')
    nb_set_menu(footprint, "orient", "xy")
    nb_set(footprint, "r", (-90.0, 0.0, 0.0))
    nb_expr(footprint, "sizex", 'ch("../width")')
    nb_expr(footprint, "sizey", 'ch("../depth")')
    nb_set(footprint, "cols", 2)
    nb_set(footprint, "rows", 2)

    # Building Mass: EXTRUDE [EXACT] -> polyextrude SOP  (Blender: GeometryNodeExtrudeMesh)
    building_mass = nb_create(geo, "polyextrude", "building_mass")
    nb_meta(building_mass, 'NodeBridge: Building Mass (EXACT)', '{"op": "EXTRUDE", "source": ["GeometryNodeExtrudeMesh"], "confidence": "EXACT"}')
    building_mass.setInput(0, footprint)
    nb_expr(building_mass, "dist", '(ch("../floors") * ch("../floor_height"))')
    nb_set_menu(building_mass, "splittype", "elements")
    nb_set(building_mass, "outputback", 0)

    # Floor Levels: PRIMITIVE [EXACT] -> line SOP  (Blender: GeometryNodeMeshLine)
    floor_levels = nb_create(geo, "line", "floor_levels")
    nb_meta(floor_levels, 'NodeBridge: Floor Levels (EXACT)', '{"op": "PRIMITIVE", "source": ["GeometryNodeMeshLine"], "confidence": "EXACT"}')
    nb_set(floor_levels, "origin", (0.0, 0.0, 0.0))
    nb_expr(floor_levels, "dir", '0', index=0)
    nb_expr(floor_levels, "dir", 'ch("../floor_height")', index=1)
    nb_expr(floor_levels, "dir", '0', index=2)
    nb_expr(floor_levels, "dist", '(ch("../floors") - 1) * abs(ch("../floor_height"))')
    nb_expr(floor_levels, "points", 'int(ch("../floors"))')

    # Floor Slab: SUBGRAPH [EXACT] -> subnet SOP with promoted parameters  (Blender: GeometryNodeGroup)
    floor_slab = nb_create(geo, "subnet", "floor_slab")
    nb_meta(floor_slab, 'NodeBridge: Floor Slab (EXACT)', '{"op": "SUBGRAPH", "source": ["GeometryNodeGroup"], "confidence": "EXACT"}')
    nb_add_parameters(floor_slab, 'FloorSlab', [
        hou.FloatParmTemplate('width', 'Width', 1, default_value=(10.0,)),
        hou.FloatParmTemplate('depth', 'Depth', 1, default_value=(8.0,)),
        hou.FloatParmTemplate('thickness', 'Thickness', 1, default_value=(0.25,)),
    ])
    nb_expr(floor_slab, "width", '(ch("../width") + 0.6)')
    nb_expr(floor_slab, "depth", '(ch("../depth") + 0.6)')
    nb_set(floor_slab, "thickness", 0.25)

    # Slab Outline: PRIMITIVE [EXACT] -> grid SOP  (Blender: GeometryNodeMeshGrid)
    slab_outline = nb_create(floor_slab, "grid", "slab_outline")
    nb_meta(slab_outline, 'NodeBridge: Slab Outline (EXACT)', '{"op": "PRIMITIVE", "source": ["GeometryNodeMeshGrid"], "confidence": "EXACT"}')
    nb_set_menu(slab_outline, "orient", "xy")
    nb_set(slab_outline, "r", (-90.0, 0.0, 0.0))
    nb_expr(slab_outline, "sizex", 'ch("../width")')
    nb_expr(slab_outline, "sizey", 'ch("../depth")')
    nb_set(slab_outline, "cols", 2)
    nb_set(slab_outline, "rows", 2)

    # Slab Thickness: EXTRUDE [EXACT] -> polyextrude SOP  (Blender: GeometryNodeExtrudeMesh)
    slab_thickness = nb_create(floor_slab, "polyextrude", "slab_thickness")
    nb_meta(slab_thickness, 'NodeBridge: Slab Thickness (EXACT)', '{"op": "EXTRUDE", "source": ["GeometryNodeExtrudeMesh"], "confidence": "EXACT"}')
    slab_thickness.setInput(0, slab_outline)
    nb_expr(slab_thickness, "dist", 'ch("../thickness")')
    nb_set_menu(slab_thickness, "splittype", "elements")
    nb_set(slab_thickness, "outputback", 0)
    floor_slab_output_0 = nb_create(floor_slab, "output", "out_slab")
    nb_set(floor_slab_output_0, "outputidx", 0)
    floor_slab_output_0.setInput(0, slab_thickness)
    floor_slab_output_0.setDisplayFlag(True)
    floor_slab.layoutChildren()

    # Stack Floors: INSTANCE [EXACT] -> copytopoints SOP (Pack and Instance)  (Blender: GeometryNodeInstanceOnPoints)
    stack_floors = nb_create(geo, "copytopoints", "stack_floors")
    nb_meta(stack_floors, 'NodeBridge: Stack Floors (EXACT)', '{"op": "INSTANCE", "source": ["GeometryNodeInstanceOnPoints"], "confidence": "EXACT"}')
    stack_floors.setInput(0, floor_slab)
    stack_floors.setInput(1, floor_levels)
    nb_set(stack_floors, "pack", 1)
    nb_set(stack_floors, "useimplicitn", 0)

    # Realize Floors: REALIZE_INSTANCES [EXACT] -> unpack SOP  (Blender: GeometryNodeRealizeInstances)
    realize_floors = nb_create(geo, "unpack", "realize_floors")
    nb_meta(realize_floors, 'NodeBridge: Realize Floors (EXACT)', '{"op": "REALIZE_INSTANCES", "source": ["GeometryNodeRealizeInstances"], "confidence": "EXACT"}')
    realize_floors.setInput(0, stack_floors)

    # Window Positions: SCATTER [EQUIVALENT] -> scatter SOP  (Blender: GeometryNodeDistributePointsOnFaces)
    window_positions_selection = nb_create(geo, "attribwrangle", "window_positions_selection")
    window_positions_selection.setInput(0, building_mass)
    nb_set(window_positions_selection, "class", 1)
    window_positions_selection_vex = NB_VEX_HEADER + NB_VEX_COORDINATES + """\
// Blender fields: Normal, Separate XYZ, Facade Facing, Is Wall
vector nb_sep1 = nb_b(prim_normal(0, @primnum, 0.5, 0.5));
setprimgroup(0, "nb_scatter_scatter_19", @primnum, ((abs(nb_sep1.z)) < 0.1), "set");
"""
    nb_set(window_positions_selection, "snippet", window_positions_selection_vex)
    window_positions = nb_create(geo, "scatter", "window_positions")
    nb_meta(window_positions, 'NodeBridge: Window Positions (EQUIVALENT)', '{"op": "SCATTER", "source": ["GeometryNodeDistributePointsOnFaces"], "confidence": "EQUIVALENT"}')
    window_positions.setInput(0, window_positions_selection)
    nb_set(window_positions, "group", 'nb_scatter_scatter_19')
    nb_set(window_positions, "forcetotal", 0)
    nb_expr(window_positions, "densityscale", 'ch("../window_density")')
    nb_expr(window_positions, "seed", 'int(ch("../seed"))')
    nb_set(window_positions, "relaxpoints", 0)

    # Window Variation: RANDOM_TRANSFORM [EQUIVALENT] -> attribwrangle writing orient / scale  (Blender: FunctionNodeRandomValue, GeometryNodeInstanceOnPoints)
    window_variation = nb_create(geo, "attribwrangle", "window_variation")
    nb_meta(window_variation, 'NodeBridge: Window Variation (EQUIVALENT)', '{"op": "RANDOM_TRANSFORM", "source": ["FunctionNodeRandomValue", "GeometryNodeInstanceOnPoints"], "confidence": "EQUIVALENT"}')
    window_variation.setInput(0, window_positions)
    nb_set(window_variation, "class", 2)
    window_variation_vex = NB_VEX_HEADER + NB_VEX_COORDINATES + NB_VEX_RANDOM + """\
int nb_id = haspointattrib(0, "id") ? point(0, "id", @ptnum) : @ptnum;
float nb_s = fit01(nb_random(chi("../seed"), nb_id, 0), 0.7, 1.2);
vector nb_scale = set(nb_s, nb_s, nb_s);
vector nb_prev = haspointattrib(0, "scale") ? point(0, "scale", @ptnum) : {1, 1, 1};
v@scale = nb_prev * nb_scale;
"""
    nb_set(window_variation, "snippet", window_variation_vex)

    # Place Windows: INSTANCE [EXACT] -> copytopoints SOP (Pack and Instance)  (Blender: GeometryNodeInstanceOnPoints)
    place_windows = nb_create(geo, "copytopoints", "place_windows")
    nb_meta(place_windows, 'NodeBridge: Place Windows (EXACT)', '{"op": "INSTANCE", "source": ["GeometryNodeInstanceOnPoints"], "confidence": "EXACT"}')
    place_windows.setInput(0, window_panel)
    place_windows.setInput(1, window_variation)
    nb_set(place_windows, "pack", 1)
    nb_set(place_windows, "useimplicitn", 0)

    # Realize Windows: REALIZE_INSTANCES [EXACT] -> unpack SOP  (Blender: GeometryNodeRealizeInstances)
    realize_windows = nb_create(geo, "unpack", "realize_windows")
    nb_meta(realize_windows, 'NodeBridge: Realize Windows (EXACT)', '{"op": "REALIZE_INSTANCES", "source": ["GeometryNodeRealizeInstances"], "confidence": "EXACT"}')
    realize_windows.setInput(0, place_windows)

    # Assemble Building: MERGE [EXACT] -> merge SOP  (Blender: GeometryNodeJoinGeometry)
    assemble_building = nb_create(geo, "merge", "assemble_building")
    nb_meta(assemble_building, 'NodeBridge: Assemble Building (EXACT)', '{"op": "MERGE", "source": ["GeometryNodeJoinGeometry"], "confidence": "EXACT"}')
    assemble_building.setInput(0, realize_windows)
    assemble_building.setInput(1, realize_floors)
    assemble_building.setInput(2, building_mass)

    # Concrete: MATERIAL_ASSIGNMENT [EQUIVALENT] -> material SOP  (Blender: GeometryNodeSetMaterial)
    concrete = nb_create(geo, "material", "concrete")
    nb_meta(concrete, 'NodeBridge: Concrete (EQUIVALENT)', '{"op": "MATERIAL_ASSIGNMENT", "source": ["GeometryNodeSetMaterial"], "confidence": "EQUIVALENT"}')
    concrete.setInput(0, assemble_building)
    nb_set(concrete, "shop_materialpath1", '/mat/concrete')

    # Geometry: GEOMETRY_OUTPUT [EXACT] -> null OUT (display/render)  (Blender: NodeGroupOutput)
    out = nb_create(geo, "null", "OUT")
    out.setInput(0, concrete)
    out.setDisplayFlag(True)
    out.setRenderFlag(True)

    geo.layoutChildren()
    nb_place_notes()
    return geo

geo = build()
print("NodeBridge: created", geo.path())
for nb_warning in NB_WARNINGS:
    print("NodeBridge warning:", nb_warning)
