# Generated by NodeBridge 0.3.0
# Houdini SOP network
# Source: geometry / BuildingGenerator
#
# Paste this script into the Houdini Python Source Editor and run it.
# It builds an editable native network. It does not import baked geometry.
# Loading a .nodebridge.json file does not execute this script.
# Coordinates: Blender Z-up right-handed -> Houdini Y-up right-handed.
#     position' = (x, z, -y)
# Units: lengths stay in meters when the source is Blender.
#     Rotations are converted from radians to degrees for Transform SOPs.
# Randomness: Scatter and Attribute Randomize do not reproduce Blender's sequence.
#     NodeBridge's hash random is emitted only into wrangles that implement random values
#     when deterministic randomness is enabled. It is not Blender's random.

import hou

def _create(parent, node_type, name):
    category = parent.childTypeCategory()
    if hou.nodeType(category, node_type) is None:
        raise hou.NodeError(
            'NodeBridge expected Houdini node type %r in %s. '
            'This build does not provide it, so the operation was not skipped silently.'
            % (node_type, parent.path())
        )
    return parent.createNode(node_type, name)

def _set(node, name, value):
    parm = node.parmTuple(name) if isinstance(value, (list, tuple)) else node.parm(name)
    if parm is None:
        parm = node.parm(name)
    if parm is None:
        return False
    parm.set(value)
    return True

def build(parent=None):
    parent = parent or hou.node('/obj')
    name = 'buildinggenerator'
    # Always create a new Geometry container. Existing scene nodes are not modified.
    geo = parent.createNode('geo', name)
    for child in list(geo.children()):
        child.destroy()
    created = {}

    # Reference implementation of NodeBridge random(seed, element_id).
    # Paste into a wrangle only where a comment below says to use it.
    # // NodeBridge deterministic random. Not Blender's or Houdini's rand().
    # int nb_mix(int value) {
    #     value = value & 0xFFFFFFFF;
    #     value = value ^ (value >> 16);
    #     value = (value * 0x7FEB352D) & 0xFFFFFFFF;
    #     value = value ^ (value >> 15);
    #     value = (value * 0x846CA68B) & 0xFFFFFFFF;
    #     value = value ^ (value >> 16);
    #     return value;
    # }
    # float nb_random(int seed; int element_id) {
    #     int mixed = nb_mix((seed * 0x9E3779B1) ^ (element_id * 0x85EBCA6B));
    #     return float(mixed & 0xFFFFFF) / 16777216.0;
    # }

    grid = _create(geo, 'grid', 'grid')
    _set(grid, 'size', [1.0, 1.0, 1.0])
    created['Grid__node'] = grid

    extrude_floors = _create(geo, 'polyextrude', 'extrude_floors')
    # EQUIVALENT: PolyExtrude matches the intent of Extrude Mesh. Inset and individual-face options are not fully reproduced.
    extrude_floors.setComment('PolyExtrude matches the intent of Extrude Mesh. Inset and individual-face options are not fully reproduced.')
    created['Extrude_Floors__node'] = extrude_floors

    subdivide = _create(geo, 'subdivide', 'subdivide')
    # APPROXIMATE: Houdini Subdivide is not Blender's subdivision algorithm.
    subdivide.setComment("Houdini Subdivide is not Blender's subdivision algorithm.")
    created['Subdivide__node'] = subdivide

    set_material = _create(geo, 'material', 'set_material')
    # EQUIVALENT: Material SOP assigns a shop material path. Blender material slots are not copied.
    set_material.setComment('Material SOP assigns a shop material path. Blender material slots are not copied.')
    _set(set_material, 'shop_materialpath1', '')
    created['Set_Material__node'] = set_material

    group_output = _create(geo, 'null', 'group_output')
    created['Group_Output__node'] = group_output

    extrude_floors.setInput(0, grid)
    subdivide.setInput(0, extrude_floors)
    set_material.setInput(0, subdivide)
    group_output.setInput(0, set_material)

    set_material.setDisplayFlag(True)
    set_material.setRenderFlag(True)
    _annotate(geo, created)
    for node in created.values():
        node.moveToGoodPosition()
    geo.layoutChildren()
    return geo

def _annotate(geo, created):
    notes = []
    for node in created.values():
        comment = node.comment()
        if comment:
            notes.append(node.name() + ': ' + comment)
    if not notes:
        return
    sticky = geo.createStickyNote()
    sticky.setText('NodeBridge\n' + '\n'.join(notes))
    sticky.setPosition(hou.Vector2(0, 2))

if __name__ == '__main__':
    build()
