# Generated by NodeBridge 0.3.0
# Unreal Editor Python — PCG
# Source: BuildingGenerator
#
# Paste into the Unreal Editor Python console or a Python asset.
# Requires the Editor Python Script Plugin and the PCG plugin.
# This creates a PCG graph asset. It does not import baked geometry.
# Surface Sampler and Static Mesh Spawner do not reproduce Blender's
# random sequence or packed instances exactly.
# add_node_of_type / add_edge are editor-only and version-sensitive.
# Loading a .nodebridge.json file does not execute this script.
import unreal

def build(asset_name=None, package_path='/Game/NodeBridge'):
    asset_name = asset_name or 'BuildingGenerator'
    if not hasattr(unreal, 'PCGGraphFactory'):
        raise RuntimeError(
            'unreal.PCGGraphFactory is not available. Enable the PCG plugin. '
            'NodeBridge will not call an undocumented factory.'
        )
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    graph = tools.create_asset(asset_name, package_path, unreal.PCGGraph, unreal.PCGGraphFactory())
    if not hasattr(graph, 'add_node_of_type'):
        raise RuntimeError(
            'PCGGraph.add_node_of_type is not available in this Unreal Editor build. '
            'NodeBridge does not guess a private graph API.'
        )
    created = {}
    input_node = graph.get_input_node()
    output_node = graph.get_output_node()
    created['input'] = input_node
    created['output'] = output_node
    # APPROXIMATE: geometry.primitive. PCG samples points from a mesh asset; it does not author a mesh primitive SOP-style.
    node, settings = graph.add_node_of_type(unreal.PCGPointFromMeshSettings)
    node.set_node_position(200, 0)
    try:
        settings.set_editor_property('primitive', 'grid')
    except Exception as exc:
        unreal.log_warning('NodeBridge could not set primitive on geometry.primitive: ' + str(exc))
    try:
        settings.set_editor_property('size', 1.0)
    except Exception as exc:
        unreal.log_warning('NodeBridge could not set size on geometry.primitive: ' + str(exc))
    created['Grid__node'] = node
    # UNSUPPORTED: geometry.extrude
    # No Unreal PCG mapping is registered. Do not invent a Material or Blueprint substitute silently.
    created['Extrude_Floors__unsupported'] = None
    # UNSUPPORTED: geometry.subdivide
    # No Unreal PCG mapping is registered. Do not invent a Material or Blueprint substitute silently.
    created['Subdivide__unsupported'] = None
    # UNSUPPORTED: geometry.set_material
    # No Unreal PCG mapping is registered. Do not invent a Material or Blueprint substitute silently.
    created['Set_Material__unsupported'] = None
    created['Group_Output__node'] = created['output']
    if created.get('Grid__node') is not None and created.get('Extrude_Floors__unsupported') is not None:
        graph.add_edge(created['Grid__node'], 'Out', created['Extrude_Floors__unsupported'], 'geometry')
    if created.get('Extrude_Floors__unsupported') is not None and created.get('Subdivide__unsupported') is not None:
        graph.add_edge(created['Extrude_Floors__unsupported'], 'geometry', created['Subdivide__unsupported'], 'geometry')
    if created.get('Subdivide__unsupported') is not None and created.get('Set_Material__unsupported') is not None:
        graph.add_edge(created['Subdivide__unsupported'], 'geometry', created['Set_Material__unsupported'], 'geometry')
    if created.get('Set_Material__unsupported') is not None and created.get('Group_Output__node') is not None:
        graph.add_edge(created['Set_Material__unsupported'], 'geometry', created['Group_Output__node'], 'Out')
    unreal.EditorAssetLibrary.save_loaded_asset(graph)
    return graph

if __name__ == '__main__':
    build()
