"""Blender Geometry Nodes backend.

Consumes lowered semantic operations and produces an editable Geometry
Nodes construction plan. Live bpy execution is optional and explicit.
"""

from __future__ import annotations

from nodebridge.backends.base import GraphFragment, TargetConnectionSpec, TargetNodeSpec
from nodebridge.core.capabilities import CapabilitySet
from nodebridge.core.diagnostics import TranslationStatus
from nodebridge.core.graph import IRGraph
from nodebridge.core.metadata import SourceMapping
from nodebridge.core.node import IRNode
from nodebridge.hosts.assemble import assemble_native
from nodebridge.hosts.blender.capabilities import blender_capabilities
from nodebridge.hosts.blender.mappings import BLENDER_RECIPES, PRIMITIVE_BACKEND_TYPES
from nodebridge.hosts.contract import Implementation, LoweringFragment
from nodebridge.hosts.native import NativeGraph
from nodebridge.hosts.recipes import unsupported_fragment
from nodebridge.ir.versioning import PACKAGE_VERSION


class BlenderBackend:
    """Generate an editable Geometry Nodes graph from canonical IR."""

    name = "blender"

    def __init__(self) -> None:
        self.capabilities: CapabilitySet = blender_capabilities()

    def implementation_for(self, operation: str) -> Implementation:
        recipe = BLENDER_RECIPES.get(operation)
        if recipe is None:
            return Implementation(
                operation=operation,
                fidelity=TranslationStatus.UNSUPPORTED,
                available=False,
                note="No Blender Geometry Nodes mapping is registered",
            )
        return recipe.implementation()

    def lower_node(self, node: IRNode) -> LoweringFragment:
        recipe = BLENDER_RECIPES.get(node.operation)
        if recipe is None:
            return unsupported_fragment(
                node, note="No Blender Geometry Nodes mapping is registered"
            )
        fragment = recipe.apply(node)
        if node.operation == "geometry.primitive":
            kind = str(node.parameters["primitive"].value) if "primitive" in node.parameters else "cube"
            native_type = PRIMITIVE_BACKEND_TYPES.get(kind, "GeometryNodeMeshCube")
            if fragment.nodes:
                fragment.nodes[0].type = native_type
                fragment.recipe = native_type
        return fragment

    def translate_node(self, node: IRNode) -> GraphFragment:
        fragment = self.lower_node(node)
        return GraphFragment(
            nodes=[
                TargetNodeSpec(id=item.id, kind=item.type, parameters=dict(item.parameters))
                for item in fragment.nodes
            ],
            connections=[
                TargetConnectionSpec(
                    source_node=link.source_node,
                    source_socket=link.source_socket,
                    target_node=link.target_node,
                    target_socket=link.target_socket,
                )
                for link in fragment.links
            ],
            status=fragment.fidelity,
            mapping=SourceMapping(
                ir_node_id=node.id,
                target_nodes=[item.id for item in fragment.nodes],
            ),
        )

    def build(self, graph: IRGraph) -> NativeGraph:
        native, _report = assemble_native(
            graph, self, host_id="blender", system="geometry_nodes"
        )
        return native

    def generate(self, graph: IRGraph) -> str:
        native = self.build(graph)
        return emit_blender_script(native)


def emit_blender_script(native: NativeGraph) -> str:
    """Deterministic bpy script. Never executed by IR load."""
    lines = [
        f"# Generated by NodeBridge {PACKAGE_VERSION}",
        "# Run inside Blender. Loading a .nodebridge.json file does not execute this.",
        "import bpy",
        "",
        "def build(tree=None):",
        f"    name = {native.name!r}",
        "    if tree is None:",
        "        tree = bpy.data.node_groups.new(name, 'GeometryNodeTree')",
        "    nodes = tree.nodes",
        "    nodes.clear()",
        "    created = {}",
    ]
    for node in native.nodes:
        lines.append(f"    node = nodes.new({node.type!r})")
        lines.append(f"    node.name = {node.id!r}")
        if node.position:
            lines.append(f"    node.location = ({node.position[0]}, {node.position[1]})")
        for key, value in node.parameters.items():
            lines.append(f"    if hasattr(node, {key!r}):")
            lines.append(f"        setattr(node, {key!r}, {value!r})")
        lines.append(f"    created[{node.id!r}] = node")
    lines.append("    links = tree.links")
    for link in native.links:
        lines.append(
            "    links.new("
            f"created[{link.source_node!r}].outputs.get({link.source_socket!r}) or "
            f"created[{link.source_node!r}].outputs[0], "
            f"created[{link.target_node!r}].inputs.get({link.target_socket!r}) or "
            f"created[{link.target_node!r}].inputs[0])"
        )
    lines.append("    return tree")
    lines.append("")
    lines.append("if __name__ == '__main__':")
    lines.append("    build()")
    lines.append("")
    return "\n".join(lines)
