"""Houdini backend: Semantic IR -> executable Houdini Python (``hou``)."""

from __future__ import annotations

import math
from typing import TYPE_CHECKING, Any

from ... import __version__
from ...common.coordinates import HOUDINI, convert_point, convert_scale
from ...common.names import NameAllocator, houdini_node_name, python_identifier
from ...common.units import ValueRole
from ...compiler.diagnostics import DiagnosticBag
from ...compiler.subgraphs import has_field_interface, inline_where
from ...ir.graph import TreeKind
from ...ir.semantic import Const, ExposedParameter, SemanticGraph, SemanticOp
from ...ir.types import GEOMETRY_TYPES, DataType
from ...translation.confidence import Confidence
from ..base import GeneratedCode, TargetBackend
from ..codegen import PyWriter, clean_number, literal
from ..registry import register_backend
from .hscript import spare_parm_name
from .runtime import HELPERS
from .sop import Network, SopBuilder, Stream
from .vex import library_definitions

if TYPE_CHECKING:
    from ...compiler.pipeline import CompilationResult


class HoudiniBackend(TargetBackend):
    id = "houdini"
    display_name = "Houdini"
    language_label = "Houdini Python"
    coordinate_system = "houdini"
    required_imports = ("hou",)
    contexts = {TreeKind.GEOMETRY: "sop", TreeKind.SHADER: "mtlx", TreeKind.COMPOSITOR: "cop2"}
    context_labels = {"sop": "SOP network", "mtlx": "MaterialX material in /mat", "cop2": "COP2 network in /img"}

    def prepare(self, graph: SemanticGraph, diagnostics: DiagnosticBag) -> SemanticGraph:
        if graph.kind == TreeKind.GEOMETRY:
            inline_where(
                graph,
                lambda g, op: has_field_interface(g, op) or not any(ref.base in GEOMETRY_TYPES for ref in op.outputs.values()),
                diagnostics,
                "SOP subnets cannot pass fields across their boundary",
            )
        else:
            inline_where(graph, lambda g, op: True, diagnostics, f"{graph.kind.label} groups are flattened in Houdini")
        return graph

    def generate(self, result: "CompilationResult") -> GeneratedCode:
        kind = result.semantic.kind
        w = PyWriter()
        self._header(w, result)
        if kind == TreeKind.GEOMETRY:
            self._geometry(w, result)
        elif kind == TreeKind.SHADER:
            from .materials import write_material_function

            w.blank()
            function = write_material_function(self, result, w, NameAllocator())
            w.blank()
            w.line("def build():")
            w.line(f"    return {function}()")
            w.blank()
            w.line("material = build()")
            w.line('print("NodeBridge: created material", material.path())')
            self._footer(w)
        else:
            from .cop import write_compositor

            write_compositor(self, result, w)
            self._footer(w)
        name = houdini_node_name(result.document.root)
        return GeneratedCode(
            target=self.id,
            language="python",
            filename=f"nodebridge_{name}_houdini.py",
            code=w.text(),
            run_instructions="Houdini: Windows > Python Source Editor, paste, then click Apply (or run in Windows > Python Shell).",
        )

    # -- script sections ----------------------------------------------------
    def _header(self, w: PyWriter, result: "CompilationResult") -> None:
        report = result.report
        counts = report.counts
        w.line('"""NodeBridge: generated Houdini Python.')
        w.line("")
        w.line(f"Source:  {report.source_kind} / {report.source_name}" + (f" ({report.source_application})" if report.source_application else ""))
        w.line(f"Target:  {report.target_label}")
        w.line(f"Translation: {counts['EXACT']} exact, {counts['EQUIVALENT']} equivalent, {counts['APPROXIMATE']} approximate, {counts['UNSUPPORTED']} unsupported")
        w.line(f"Generated by NodeBridge {__version__}.")
        w.line("")
        w.line("Run inside Houdini: Windows > Python Source Editor, paste this script, click Apply.")
        w.line("The script only creates new nodes; existing scene content is not modified.")
        w.line("Equivalent / approximate operations are marked with sticky notes in the network.")
        w.line('"""')
        w.line("import hou")
        w.blank()
        w.block(HELPERS)
        w.blank()

    def _footer(self, w: PyWriter) -> None:
        w.line("for nb_warning in NB_WARNINGS:")
        w.line('    print("NodeBridge warning:", nb_warning)')

    def _geometry(self, w: PyWriter, result: "CompilationResult") -> None:
        graph = result.semantic
        variables = NameAllocator({"obj", "geo", "hou", "build", "materials"})
        libraries: set[str] = set()
        library_mark = w.mark()
        material_exprs: dict[str, str] = {}
        if result.materials:
            from .materials import write_material_function

            w.blank()
            w.line("def build_materials():")
            w.indent()
            w.line('"""Materials referenced by Set Material nodes."""')
            w.line("created = {}")
            for name, sub in result.materials.items():
                w.blank()
                inner = PyWriter()
                function = write_material_function(self, sub, inner, NameAllocator(), nested=True)
                w.block(inner.text())
                w.line(f"created[{name!r}] = {function}().path()")
            w.line("return created")
            w.dedent()
            for name in result.materials:
                material_exprs[name] = f"materials.get({name!r}, '/mat/{houdini_node_name(name)}')"
        w.blank()
        w.line("def build():")
        w.indent()
        w.line('obj = hou.node("/obj")')
        w.line(f'geo = nb_create(obj, "geo", "{houdini_node_name("nb_" + graph.name)}", run_init_scripts=False)')
        templates = parameter_templates(graph.parameters)
        if any(op.kind == "GEOMETRY_INPUT" for op in graph.ops.values()):
            templates.append('hou.ToggleParmTemplate("use_source_object", "Use Source Object", default_value=False)')
        if templates:
            w.line(f"nb_add_parameters(geo, {graph.name!r}, [")
            w.indent()
            for template in templates:
                w.line(template + ",")
            w.dedent()
            w.line("])")
        if result.materials:
            w.line("materials = build_materials()")
        builder = SopBuilder(self, result, graph, w, Network("geo", graph.name, graph.parameters), variables, libraries=libraries)
        builder.materials = material_exprs
        builder.build()
        w.blank()
        w.line("geo.layoutChildren()" if result.options.organize_graph else "for child in geo.children(): child.moveToGoodPosition()")
        w.line("nb_place_notes()")
        w.line("return geo")
        w.dedent()
        w.blank()
        w.line("geo = build()")
        w.line('print("NodeBridge: created", geo.path())')
        self._footer(w)
        if libraries:
            w.insert(library_mark, library_definitions(libraries))


def parameter_templates(parameters: list[ExposedParameter]) -> list[str]:
    templates = []
    for p in parameters:
        name = spare_parm_name(p.key)
        label = p.name
        value = p.current
        bounds = _bounds(p)
        if p.data_type == DataType.FLOAT:
            default = _convert_param_scalar(value, p.role)
            templates.append(f"hou.FloatParmTemplate({name!r}, {label!r}, 1, default_value=({literal(default)},){bounds})")
        elif p.data_type == DataType.INT:
            templates.append(f"hou.IntParmTemplate({name!r}, {label!r}, 1, default_value=({int(value or 0)},){bounds})")
        elif p.data_type == DataType.BOOL:
            templates.append(f"hou.ToggleParmTemplate({name!r}, {label!r}, default_value={bool(value)})")
        elif p.data_type in (DataType.VECTOR3, DataType.ROTATION):
            default = _convert_param_vector(value, p.role)
            templates.append(f"hou.FloatParmTemplate({name!r}, {label!r}, 3, default_value={literal(default)})")
        elif p.data_type == DataType.COLOR:
            rgb = tuple(clean_number(float(c)) for c in (list(value or [1, 1, 1]) + [1, 1, 1])[:3])
            templates.append(f"hou.FloatParmTemplate({name!r}, {label!r}, 3, default_value={literal(rgb)}, look=hou.parmLook.ColorSquare, naming_scheme=hou.parmNamingScheme.RGBA)")
        else:
            text = value.get("name", "") if isinstance(value, dict) else ("" if value is None else str(value))
            templates.append(f"hou.StringParmTemplate({name!r}, {label!r}, 1, default_value=({text!r},))")
    return templates


def _bounds(p: ExposedParameter) -> str:
    parts = []
    for key, value in (("min", p.min_value), ("max", p.max_value)):
        if isinstance(value, (int, float)) and math.isfinite(value) and abs(value) < 1e6:
            converted = _convert_param_scalar(value, p.role) if p.data_type == DataType.FLOAT else int(value)
            parts.append(f"{key}={literal(converted)}")
    return (", " + ", ".join(parts)) if parts else ""


def _convert_param_scalar(value: Any, role: ValueRole) -> float:
    number = float(value or 0.0)
    if role == ValueRole.ANGLE:
        return clean_number(math.degrees(number))
    return clean_number(number)


def _convert_param_vector(value: Any, role: ValueRole) -> tuple:
    items = [float(v) for v in (list(value or [0, 0, 0]) + [0, 0, 0])[:3]]
    if role in (ValueRole.POSITION, ValueRole.DIRECTION, ValueRole.NORMAL):
        items = list(convert_point(items, target=HOUDINI))
    elif role == ValueRole.SCALE:
        items = list(convert_scale(items, target=HOUDINI))
    elif role == ValueRole.EULER:
        items = [math.degrees(items[0]), math.degrees(items[2]), -math.degrees(items[1])]
    return tuple(clean_number(v) for v in items)


def build_subnet(b: SopBuilder, op: SemanticOp) -> None:
    """A node group instance becomes a SOP subnet with promoted parameters."""
    sub = b.graph.subgraphs[op.params["graph"]]
    var = b.node(op, "subnet")
    inputs = [o for o in sub.ops.values() if o.kind == "GEOMETRY_INPUT"]
    for index, inner in enumerate(inputs):
        inner.annotations["subnet_input"] = index
        b.connect(var, index, b.stream_for(op.inputs.get(inner.params.get("identifier", ""))))
    templates = parameter_templates(sub.parameters)
    if templates:
        b.w.line(f"nb_add_parameters({var}, {sub.name!r}, [")
        b.w.indent()
        for template in templates:
            b.w.line(template + ",")
        b.w.dedent()
        b.w.line("])")
    for parameter in sub.parameters:
        value = op.inputs.get(parameter.identifier)
        if value is None:
            continue
        count = 3 if parameter.data_type in (DataType.VECTOR3, DataType.COLOR, DataType.ROTATION) else 1
        integer = parameter.data_type in (DataType.INT, DataType.BOOL)
        if isinstance(value, Const) and count == 1 and not integer:
            b.set(var, spare_parm_name(parameter.key), _convert_param_scalar(value.value, parameter.role))
        elif isinstance(value, Const) and count == 3:
            b.set(var, spare_parm_name(parameter.key), _convert_param_vector(value.value, parameter.role))
        else:
            b.set_value(var, spare_parm_name(parameter.key), value, parameter.role, count=count, default=parameter.current, integer=integer)
    inputs_var = f"{var}_inputs"
    b.w.line(f"{inputs_var} = {var}.indirectInputs()")
    inner = SopBuilder(b.backend, b.result, sub, b.w, Network(var, sub.name, sub.parameters), b.vars, in_subnet=True, libraries=b.libraries)
    inner.indirect_inputs = inputs_var
    inner.materials = b.materials
    inner.build()
    outputs = [out for out in sub.outputs if out.data_type in GEOMETRY_TYPES]
    for index, out in enumerate(outputs):
        stream = inner.stream_for(out.value)
        node = b.vars.allocate(python_identifier(f"{var}_output_{index}"))
        b.w.line(f'{node} = nb_create({var}, "output", "{houdini_node_name("OUT_" + (out.label or out.name))}")')
        b.w.line(f'nb_set({node}, "outputidx", {index})')
        if stream is not None:
            b.connect(node, 0, stream)
        if index == 0:
            b.w.line(f"{node}.setDisplayFlag(True)")
        b.set_output(op, out.name, var, index)
    b.w.line(f"{var}.layoutChildren()")


register_backend(HoudiniBackend())
